package com.rent.services;

import java.util.List;

import com.rent.condition.TempCondition;
import com.rent.entity.PrHouse;
import com.rent.entity.RmdevTemp;

public interface RmdevTempService {

	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMDEV_TEMP
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    List<RmdevTemp> findByRoid(Integer roid);
    
    List<RmdevTemp> findByRoidAndPaged(TempCondition condition,Integer currage,Integer size);
    //ʹ��ģ�����������
    
    boolean addTempList(List<RmdevTemp> temp,Integer houseid);
    //ʹ��ģ�弯�� ��ģ�����������
    boolean insertRmdevModel(List<RmdevTemp> temp,Integer houseid);
    Integer findMaxId();

	Integer moreAdd(List<RmdevTemp> temp, List<PrHouse> houses);

	int delRmdevTemp(Integer[] ids);
	
	RmdevTemp findById(Integer id);
	
	void editTemplate(Integer[] pId,Integer [] nums,Integer roomId);
	
	 Integer delByRoomType(Integer typeId);
}
