prompt Disabling triggers for USERS...
alter table USERS disable all triggers;
prompt Disabling foreign key constraints for USERS...
alter table USERS disable constraint SYS_C005239;
prompt Deleting USERS...
delete from USERS;
commit;
prompt Loading USERS...
insert into USERS (id, name, pwd, sex, phone, address, estate_id, roles, createuser, createtime, updateuser, updatetime, del)
values (1, 'admin', '49ba59abbe56e057', null, null, null, null, '1', null, null, null, null, 0);
commit;
prompt 1 records loaded
prompt Enabling foreign key constraints for USERS...
alter table USERS enable constraint SYS_C005239;
prompt Enabling triggers for USERS...
alter table USERS enable all triggers;
