package com.rent.entity;

import java.util.Date;

public class Attachment {
    
	public Attachment() {
		super();
	}



	public Attachment(PrhMaster master, Integer id, String name, Short type, Integer masterId, String uploadTime,
			String remark) {
		super();
		this.master = master;
		this.id = id;
		this.name = name;
		this.type = type;
		this.masterId = masterId;
		this.uploadTime = uploadTime;
		this.remark = remark;
	}



	private PrhMaster master;
	
	
	
	private Integer id;
	
    private String name;

    private String realName;
    
    private Short type;


    private Integer masterId;

    private String uploadTime;

  
    private String remark;
    
    
    public String getRealName() {
		return realName;
	}



	public void setRealName(String realName) {
		this.realName = realName;
	}



	public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.NAME
     *
     * @return the value of ATTACHMENT.NAME
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.NAME
     *
     * @param name the value for ATTACHMENT.NAME
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.TYPE
     *
     * @return the value of ATTACHMENT.TYPE
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.TYPE
     *
     * @param type the value for ATTACHMENT.TYPE
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.MASTER_ID
     *
     * @return the value of ATTACHMENT.MASTER_ID
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.MASTER_ID
     *
     * @param masterId the value for ATTACHMENT.MASTER_ID
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.UPLOAD_TIME
     *
     * @return the value of ATTACHMENT.UPLOAD_TIME
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.REMARK
     *
     * @return the value of ATTACHMENT.REMARK
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    public String getUploadTime() {
		return uploadTime;
	}

	public void setUploadTime(String uploadTime) {
		this.uploadTime = uploadTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.REMARK
     *
     * @param remark the value for ATTACHMENT.REMARK
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    public PrhMaster getMaster() {
		return master;
	}

	public void setMaster(PrhMaster master) {
		this.master = master;
	}
}