package com.rent.entity;

public class Building {
	
    public Building() {
		super();
	}

	public Building(String id, String name, String buildingnocode,
			Integer estateId,  String remark) {
		super();
		this.id = id;
		this.name = name;
		this.buildingnocode = buildingnocode;
		this.estateId = estateId;
		this.remark = remark;
	}
	
	private Integer positionX;
	
	private Integer positionY;
	
	
	public Integer getPositionX() {
		return positionX;
	}

	public void setPositionX(Integer positionX) {
		this.positionX = positionX;
	}

	public Integer getPositionY() {
		return positionY;
	}

	public void setPositionY(Integer positionY) {
		this.positionY = positionY;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING.BUILDINGNOCODE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String buildingnocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING.ESTATE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private Integer estateId;

    private Estate estate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING.ID
     *
     * @return the value of BUILDING.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING.ID
     *
     * @param id the value for BUILDING.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING.NAME
     *
     * @return the value of BUILDING.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING.NAME
     *
     * @param name the value for BUILDING.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING.BUILDINGNOCODE
     *
     * @return the value of BUILDING.BUILDINGNOCODE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getBuildingnocode() {
        return buildingnocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING.BUILDINGNOCODE
     *
     * @param buildingnocode the value for BUILDING.BUILDINGNOCODE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setBuildingnocode(String buildingnocode) {
        this.buildingnocode = buildingnocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING.ESTATE_ID
     *
     * @return the value of BUILDING.ESTATE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public Integer getEstateId() {
        return estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING.ESTATE_ID
     *
     * @param estateId the value for BUILDING.ESTATE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setEstateId(Integer estateId) {
        this.estateId = estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING.REMARK
     *
     * @return the value of BUILDING.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }
    
    public Estate getEstate() {
		return estate;
	}

	public void setEstate(Estate estate) {
		this.estate = estate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING.REMARK
     *
     * @param remark the value for BUILDING.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}