package com.rent.entity;

import java.math.BigDecimal;

public class BuildingNo {
   
	
	public BuildingNo() {
		super();
	}

	public BuildingNo(String id, String name, String descript,
			Integer estateId, BigDecimal monthPay, String remark) {
		super();
		this.id = id;
		this.name = name;
		this.descript = descript;
		this.estateId = estateId;	
		this.monthPay = monthPay;
		this.remark = remark;
	}

	
	
	public BuildingNo(String buildingId, String id, String name, String descript, Integer estateId, Estate estate,
			BigDecimal monthPay, String remark) {
		super();
		this.buildingId = buildingId;
		this.id = id;
		this.name = name;
		this.descript = descript;
		this.estateId = estateId;
		this.estate = estate;
		this.monthPay = monthPay;
		this.remark = remark;
	}
	
	
	private String buildingId;
	
	private Building building;
	
	private String unitName;
	
	
	
	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getBuildingId() {
		return buildingId;
	}

	public void setBuildingId(String buildingId) {
		this.buildingId = buildingId;
	}

	public Building getBuilding() {
		return building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.DESCRIPT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.ESTATE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private Integer estateId;

    
    private Estate estate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.MONTH_PAY
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private BigDecimal monthPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_NO.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String remark;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

   
    public String getName() {
        return name;
    }

 
    public void setName(String name) {
        this.name = name;
    }

    
    public String getDescript() {
        return descript;
    }

    public void setDescript(String descript) {
        this.descript = descript;
    }

  
    public Integer getEstateId() {
        return estateId;
    }

    
    public void setEstateId(Integer estateId) {
        this.estateId = estateId;
    }

    public BigDecimal getMonthPay() {
        return monthPay;
    }

    public void setMonthPay(BigDecimal monthPay) {
        this.monthPay = monthPay;
    }

    public String getRemark() {
        return remark;
    }

   
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public Estate getEstate() {
		return estate;
	}

	public void setEstate(Estate estate) {
		this.estate = estate;
	}
    
}