package com.rent.entity;

public class BuildingFloor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_FLOOR.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_FLOOR.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_FLOOR.ENGLISH_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUILDING_FLOOR.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING_FLOOR.ID
     *
     * @return the value of BUILDING_FLOOR.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING_FLOOR.ID
     *
     * @param id the value for BUILDING_FLOOR.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING_FLOOR.NAME
     *
     * @return the value of BUILDING_FLOOR.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUILDING_FLOOR.NAME
     *
     * @param name the value for BUILDING_FLOOR.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUILDING_FLOOR.ENGLISH_NAME
     *
     * @return the value of BUILDING_FLOOR.ENGLISH_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getEnglishName() {
        return englishName;
    }

   
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

  
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

	public BuildingFloor(Integer id, String name, String englishName,
			String remark) {
		super();
		this.id = id;
		this.name = name;
		this.englishName = englishName;
		this.remark = remark;
	}

	public BuildingFloor() {
		super();
	}
    
    
}