package com.rent.entity;

import java.util.Date;

public class Card {
   
	
	public Card() {
		super();
	}

	
	public Card(Integer id, Integer masterId, Integer linkId,Integer type, Integer state) {
		super();
		this.id = id;
		this.masterId = masterId;
		this.linkId = linkId;
		this.state = state;
		this.type=type;
	}
	public Card(Integer id, Integer masterId, Integer linkId,Integer type, Integer state,String idenPwd,Integer oldCardId) {
		super();
		this.id = id;
		this.masterId = masterId;
		this.linkId = linkId;
		this.state = state;
		this.type=type;
		this.idenPwd=idenPwd;
		this.oldCardId=oldCardId;
	}
	public Card(Integer id, Integer masterId, Integer linkId, Integer state, String createuser, Date createtime,
			String updateuser, Date updatetime) {
		super();
		this.id = id;
		this.masterId = masterId;
		this.linkId = linkId;
		this.state = state;
		
	}
	private Integer type;
	private String idenPwd;
	private Integer oldCardId;
	
    public Integer getOldCardId() {
		return oldCardId;
	}


	public void setOldCardId(Integer oldCardId) {
		this.oldCardId = oldCardId;
	}


	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getIdenPwd() {
		return idenPwd;
	}

	public void setIdenPwd(String idenPwd) {
		this.idenPwd = idenPwd;
	}

	private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.MASTER_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    private Integer masterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.LINK_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    private Integer linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.STATE
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CREATEUSER
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    private String createuser;

 
    private Date createtime;

    
    private String updateuser;

  
    private Date updatetime;

  
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.ID
     *
     * @param id the value for CARD.ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.MASTER_ID
     *
     * @return the value of CARD.MASTER_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.MASTER_ID
     *
     * @param masterId the value for CARD.MASTER_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.LINK_ID
     *
     * @return the value of CARD.LINK_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.LINK_ID
     *
     * @param linkId the value for CARD.LINK_ID
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.STATE
     *
     * @return the value of CARD.STATE
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.STATE
     *
     * @param state the value for CARD.STATE
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CREATEUSER
     *
     * @return the value of CARD.CREATEUSER
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CREATEUSER
     *
     * @param createuser the value for CARD.CREATEUSER
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CREATETIME
     *
     * @return the value of CARD.CREATETIME
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CREATETIME
     *
     * @param createtime the value for CARD.CREATETIME
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.UPDATEUSER
     *
     * @return the value of CARD.UPDATEUSER
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.UPDATEUSER
     *
     * @param updateuser the value for CARD.UPDATEUSER
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.UPDATETIME
     *
     * @return the value of CARD.UPDATETIME
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.UPDATETIME
     *
     * @param updatetime the value for CARD.UPDATETIME
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}