package com.rent.entity;

public class CostCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COST_CODE.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COST_CODE.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COST_CODE.ID
     *
     * @return the value of COST_CODE.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COST_CODE.ID
     *
     * @param id the value for COST_CODE.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COST_CODE.NAME
     *
     * @return the value of COST_CODE.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COST_CODE.NAME
     *
     * @param name the value for COST_CODE.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}