package com.rent.entity;

import java.math.BigDecimal;

public class Equipment {

	
	public Equipment() {
		super();
	}

	public Equipment( Integer id,Integer type, String name, BigDecimal price) {
		super();
		this.type = type;
		this.id = id;
		this.name = name;
		this.price = price;
	}

	private Integer type;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUIPMENT.ID
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUIPMENT.NAME
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUIPMENT.PRICE
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUIPMENT.ID
     *
     * @return the value of EQUIPMENT.ID
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUIPMENT.ID
     *
     * @param id the value for EQUIPMENT.ID
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUIPMENT.NAME
     *
     * @return the value of EQUIPMENT.NAME
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUIPMENT.NAME
     *
     * @param name the value for EQUIPMENT.NAME
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUIPMENT.PRICE
     *
     * @return the value of EQUIPMENT.PRICE
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUIPMENT.PRICE
     *
     * @param price the value for EQUIPMENT.PRICE
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
    
    
}