package com.rent.entity;

public class Estate {
    
    public Estate() {
		super();
	}

	public Estate(Integer id, String name, Integer typeId, EstateType estateType, String address, String remark,
			Double price) {
		super();
		this.id = id;
		this.name = name;
		this.typeId = typeId;
		this.estateType = estateType;
		this.address = address;
		this.remark = remark;
		this.price = price;
	}

	private Integer id;

    private String name;
    
    private Integer typeId;

    private EstateType estateType;
    
    private String phone; 
  
    private String address;

    
    private String remark;

    private Double price;
    
    private String authorCode;
    
    private String mapPic;
    
    
    public String getMapPic() {
		return mapPic;
	}

	public void setMapPic(String mapPic) {
		this.mapPic = mapPic;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAuthorCode() {
		return authorCode;
	}

	public void setAuthorCode(String authorCode) {
		this.authorCode = authorCode;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE.ID
     *
     * @param id the value for ESTATE.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE.NAME
     *
     * @return the value of ESTATE.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE.NAME
     *
     * @param name the value for ESTATE.NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE.TYPE_ID
     *
     * @return the value of ESTATE.TYPE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE.TYPE_ID
     *
     * @param typeId the value for ESTATE.TYPE_ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE.ADDRESS
     *
     * @return the value of ESTATE.ADDRESS
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE.ADDRESS
     *
     * @param address the value for ESTATE.ADDRESS
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE.REMARK
     *
     * @return the value of ESTATE.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE.REMARK
     *
     * @param remark the value for ESTATE.REMARK
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public EstateType getEstateType() {
		return estateType;
	}

	public void setEstateType(EstateType estateType) {
		this.estateType = estateType;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
   
    
}