package com.rent.entity;

public class EstateType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTATE_TYPE.ID
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTATE_TYPE.NAME
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE_TYPE.ID
     *
     * @return the value of ESTATE_TYPE.ID
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE_TYPE.ID
     *
     * @param id the value for ESTATE_TYPE.ID
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTATE_TYPE.NAME
     *
     * @return the value of ESTATE_TYPE.NAME
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTATE_TYPE.NAME
     *
     * @param name the value for ESTATE_TYPE.NAME
     *
     * @mbggenerated Tue Apr 25 18:10:10 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}