package com.rent.entity;

import java.util.Date;

public class HistoryIdenPwd {
	
	
    public HistoryIdenPwd() {
		super();
	}

	public HistoryIdenPwd(Integer id, Integer masterId, Integer linkId, String idenPwd, Integer createUser,
			Date createTime) {
		super();
		this.id = id;
		this.masterId = masterId;
		this.linkId = linkId;
		this.idenPwd = idenPwd;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	private String userName;
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private Integer id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.MASTER_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private Integer masterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.LINK_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private Integer linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private String idenPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.CREATE_USER
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY_IDEN_PWD.CREATE_TIME
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.ID
     *
     * @return the value of HISTORY_IDEN_PWD.ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.ID
     *
     * @param id the value for HISTORY_IDEN_PWD.ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.MASTER_ID
     *
     * @return the value of HISTORY_IDEN_PWD.MASTER_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.MASTER_ID
     *
     * @param masterId the value for HISTORY_IDEN_PWD.MASTER_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.LINK_ID
     *
     * @return the value of HISTORY_IDEN_PWD.LINK_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.LINK_ID
     *
     * @param linkId the value for HISTORY_IDEN_PWD.LINK_ID
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.IDEN_PWD
     *
     * @return the value of HISTORY_IDEN_PWD.IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public String getIdenPwd() {
        return idenPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.IDEN_PWD
     *
     * @param idenPwd the value for HISTORY_IDEN_PWD.IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setIdenPwd(String idenPwd) {
        this.idenPwd = idenPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.CREATE_USER
     *
     * @return the value of HISTORY_IDEN_PWD.CREATE_USER
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.CREATE_USER
     *
     * @param createUser the value for HISTORY_IDEN_PWD.CREATE_USER
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY_IDEN_PWD.CREATE_TIME
     *
     * @return the value of HISTORY_IDEN_PWD.CREATE_TIME
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY_IDEN_PWD.CREATE_TIME
     *
     * @param createTime the value for HISTORY_IDEN_PWD.CREATE_TIME
     *
     * @mbggenerated Fri Jun 23 15:42:34 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}