package com.rent.entity;

import java.util.Date;

public class HouseSpace {
	
	public HouseSpace() {
		super();
	}
	
	public HouseSpace( Integer id, Integer houseId, Date beginDate, Date endDate) {
		super();
		this.id = id;
		this.houseId = houseId;
		this.beginDate = beginDate;
		this.endDate = endDate;
	}

	private PrHouse prHouse;
	
    public PrHouse getPrHouse() {
		return prHouse;
	}

	public void setPrHouse(PrHouse prHouse) {
		this.prHouse = prHouse;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_SPACE.ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_SPACE.HOUSE_ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_SPACE.BEGIN_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOUSE_SPACE.END_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_SPACE.ID
     *
     * @return the value of HOUSE_SPACE.ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_SPACE.ID
     *
     * @param id the value for HOUSE_SPACE.ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_SPACE.HOUSE_ID
     *
     * @return the value of HOUSE_SPACE.HOUSE_ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_SPACE.HOUSE_ID
     *
     * @param houseId the value for HOUSE_SPACE.HOUSE_ID
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_SPACE.BEGIN_DATE
     *
     * @return the value of HOUSE_SPACE.BEGIN_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_SPACE.BEGIN_DATE
     *
     * @param beginDate the value for HOUSE_SPACE.BEGIN_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOUSE_SPACE.END_DATE
     *
     * @return the value of HOUSE_SPACE.END_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOUSE_SPACE.END_DATE
     *
     * @param endDate the value for HOUSE_SPACE.END_DATE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}