package com.rent.entity;

import java.util.Date;

public class PrhLinkman {
	
	
	private String photo;
	
	private Integer del;
	
	private Date addtime;
	
	private Date deltime;
	
	private Profile profile;
	private PrhMaster prhMaster;
	private Card card;
	
	private SubsidyType subsidyType;
  
	private String subsidyTypeId;

	
	private Card identityCard;
	
    private Integer id;

    
    public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Integer getDel() {
		return del;
	}

	public void setDel(Integer del) {
		this.del = del;
	}

	public Date getAddtime() {
		return addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Date getDeltime() {
		return deltime;
	}

	public void setDeltime(Date deltime) {
		this.deltime = deltime;
	}

	public Card getIdentityCard() {
		return identityCard;
	}

	public void setIdentityCard(Card identityCard) {
		this.identityCard = identityCard;
	}

	public Card getCard() {
		return card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.MASTER_ID
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private Integer masterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.GUESTNO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String guestno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.FLAG
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.LINK
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.ARRDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private Date arrdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.REFER
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String refer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.STA
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.DEPDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private Date depdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.ARRFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String arrfileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.DEPFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private String depfileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.HOME
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private Integer home;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_LINKMAN.HOMES
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    private Integer homes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.ID
     *
     * @return the value of PRH_LINKMAN.ID
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.ID
     *
     * @param id the value for PRH_LINKMAN.ID
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.MASTER_ID
     *
     * @return the value of PRH_LINKMAN.MASTER_ID
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.MASTER_ID
     *
     * @param masterId the value for PRH_LINKMAN.MASTER_ID
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.GUESTNO
     *
     * @return the value of PRH_LINKMAN.GUESTNO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getGuestno() {
        return guestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.GUESTNO
     *
     * @param guestno the value for PRH_LINKMAN.GUESTNO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setGuestno(String guestno) {
        this.guestno = guestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.FLAG
     *
     * @return the value of PRH_LINKMAN.FLAG
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.FLAG
     *
     * @param flag the value for PRH_LINKMAN.FLAG
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.LINK
     *
     * @return the value of PRH_LINKMAN.LINK
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.LINK
     *
     * @param link the value for PRH_LINKMAN.LINK
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.ARRDATE
     *
     * @return the value of PRH_LINKMAN.ARRDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Date getArrdate() {
        return arrdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.ARRDATE
     *
     * @param arrdate the value for PRH_LINKMAN.ARRDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setArrdate(Date arrdate) {
        this.arrdate = arrdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.REFER
     *
     * @return the value of PRH_LINKMAN.REFER
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getRefer() {
        return refer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.REFER
     *
     * @param refer the value for PRH_LINKMAN.REFER
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setRefer(String refer) {
        this.refer = refer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.STA
     *
     * @return the value of PRH_LINKMAN.STA
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.STA
     *
     * @param sta the value for PRH_LINKMAN.STA
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setSta(String sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.DEPDATE
     *
     * @return the value of PRH_LINKMAN.DEPDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Date getDepdate() {
        return depdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.DEPDATE
     *
     * @param depdate the value for PRH_LINKMAN.DEPDATE
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setDepdate(Date depdate) {
        this.depdate = depdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.ARRFILENO
     *
     * @return the value of PRH_LINKMAN.ARRFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getArrfileno() {
        return arrfileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.ARRFILENO
     *
     * @param arrfileno the value for PRH_LINKMAN.ARRFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setArrfileno(String arrfileno) {
        this.arrfileno = arrfileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.DEPFILENO
     *
     * @return the value of PRH_LINKMAN.DEPFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public String getDepfileno() {
        return depfileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.DEPFILENO
     *
     * @param depfileno the value for PRH_LINKMAN.DEPFILENO
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setDepfileno(String depfileno) {
        this.depfileno = depfileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.HOME
     *
     * @return the value of PRH_LINKMAN.HOME
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Integer getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.HOME
     *
     * @param home the value for PRH_LINKMAN.HOME
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setHome(Integer home) {
        this.home = home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_LINKMAN.HOMES
     *
     * @return the value of PRH_LINKMAN.HOMES
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public Integer getHomes() {
        return homes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_LINKMAN.HOMES
     *
     * @param homes the value for PRH_LINKMAN.HOMES
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    public void setHomes(Integer homes) {
        this.homes = homes;
    }

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public PrhMaster getPrhMaster() {
		return prhMaster;
	}

	public void setPrhMaster(PrhMaster prhMaster) {
		this.prhMaster = prhMaster;
	}

	public SubsidyType getSubsidyType() {
		return subsidyType;
	}

	public void setSubsidyType(SubsidyType subsidyType) {
		this.subsidyType = subsidyType;
	}

	public String getSubsidyTypeId() {
		return subsidyTypeId;
	}

	public void setSubsidyTypeId(String subsidyTypeId) {
		this.subsidyTypeId = subsidyTypeId;
	}
    
}