package com.rent.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class PrhMaster {
	
	private String batch;
	
	private Double	collectMoney; 
	
	private Integer rentMonth;
	
	private Double tuidesposit;
	
	private Double tuimoney;
	private Date tuidate;
	
	
	private String linkManNames;
	
	private PrHouse prHouse;
	
	private Profile profile;
	
	private RentPayWay rentPayWay;
	
	private SubsidyType subsidyType;
	
	private Integer subsidyTypeId;
	
	private Integer oldMasterId;
	
	private Integer newMasterId;
	
    private Integer id;

    private Card card;
    private Card identityCard;
    
    private String createuser;

    
    private Date createtime;

    private String updateuser;

  
    private Date updatetime;

    private Date deadlineofRent;
    private Date deadlineofLock;
    
    
   


	public String getBatch() {
		return batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public Double getCollectMoney() {
		return collectMoney;
	}

	public void setCollectMoney(Double collectMoney) {
		this.collectMoney = collectMoney;
	}

	public Double getTuimoney() {
		return tuimoney;
	}

	public void setTuimoney(Double tuimoney) {
		this.tuimoney = tuimoney;
	}

	public Date getTuidate() {
		return tuidate;
	}

	public void setTuidate(Date tuidate) {
		this.tuidate = tuidate;
	}

	public String getLinkManNames() {
		return linkManNames;
	}

	public void setLinkManNames(String linkManNames) {
		this.linkManNames = linkManNames;
	}

	public String getCreateuser() {
		return createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getUpdateuser() {
		return updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Card getIdentityCard() {
		return identityCard;
	}

	public void setIdentityCard(Card identityCard) {
		this.identityCard = identityCard;
	}

	public Card getCard() {
		return card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Integer getNewMasterId() {
		return newMasterId;
	}

	public void setNewMasterId(Integer newMasterId) {
		this.newMasterId = newMasterId;
	}

	public RentPayWay getRentPayWay() {
		return rentPayWay;
	}

	public void setRentPayWay(RentPayWay rentPayWay) {
		this.rentPayWay = rentPayWay;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.ORG_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.GUEST_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String guestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.HOUSE_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.STA
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.TYPE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.SRC
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String fileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date bdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.EDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date edate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.SETRATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private BigDecimal setrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REASON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.NUMBS
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Integer numbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.ARRTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date arrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEP
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date dep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.ARR1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date arr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEP1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date dep1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEPOSIT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RENT_CODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Integer rentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RENT_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date rentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PAYMENT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.EXPEND
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private BigDecimal expend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CRT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String crt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CRTTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date crttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RES
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String res;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RESTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date restime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String con;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CONTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date contime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CI
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String ci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CITIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date citime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String co;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.COTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date cotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.LOGID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.LOG_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String logName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.LOG_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.LOG_MARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Integer logMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BANK_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String bankFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BANK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BANK_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEP_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String depFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEP_APPLY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date depApply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DEP_FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String depFileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REL_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String relFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.RELID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String relid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REL_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date relDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REFER1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String refer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REFER2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String refer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REFER3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String refer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.REFER4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String refer4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BDATE2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date bdate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.CUSNO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String cusno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PRCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String prcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PDCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String pdcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.LOG_UPDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date logUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.BANK_REF
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String bankRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.TAG1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String tag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.TAG2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String tag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.TAG3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String tag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.TAG4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String tag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PIC_IDENTITY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String picIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PIC_PHOTO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String picPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.PHYSICS_CARD_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String physicsCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.DOOR_LOCK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private String doorLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_MASTER.UPDATE_USER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    private Integer updateUser;

    
    
   
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.ID
     *
     * @return the value of PRH_MASTER.ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.ID
     *
     * @param id the value for PRH_MASTER.ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.ORG_ID
     *
     * @return the value of PRH_MASTER.ORG_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.ORG_ID
     *
     * @param orgId the value for PRH_MASTER.ORG_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.GUEST_NO
     *
     * @return the value of PRH_MASTER.GUEST_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getGuestNo() {
        return guestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.GUEST_NO
     *
     * @param guestNo the value for PRH_MASTER.GUEST_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setGuestNo(String guestNo) {
        this.guestNo = guestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.HOUSE_ID
     *
     * @return the value of PRH_MASTER.HOUSE_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.HOUSE_ID
     *
     * @param houseId the value for PRH_MASTER.HOUSE_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.STA
     *
     * @return the value of PRH_MASTER.STA
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.STA
     *
     * @param sta the value for PRH_MASTER.STA
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setSta(String sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.TYPE
     *
     * @return the value of PRH_MASTER.TYPE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.TYPE
     *
     * @param type the value for PRH_MASTER.TYPE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.SRC
     *
     * @return the value of PRH_MASTER.SRC
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.SRC
     *
     * @param src the value for PRH_MASTER.SRC
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.FILE_NO
     *
     * @return the value of PRH_MASTER.FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getFileNo() {
        return fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.FILE_NO
     *
     * @param fileNo the value for PRH_MASTER.FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setFileNo(String fileNo) {
        this.fileNo = fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BDATE
     *
     * @return the value of PRH_MASTER.BDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getBdate() {
        return bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BDATE
     *
     * @param bdate the value for PRH_MASTER.BDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.EDATE
     *
     * @return the value of PRH_MASTER.EDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.EDATE
     *
     * @param edate the value for PRH_MASTER.EDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RATE
     *
     * @return the value of PRH_MASTER.RATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RATE
     *
     * @param rate the value for PRH_MASTER.RATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.SETRATE
     *
     * @return the value of PRH_MASTER.SETRATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public BigDecimal getSetrate() {
        return setrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.SETRATE
     *
     * @param setrate the value for PRH_MASTER.SETRATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setSetrate(BigDecimal setrate) {
        this.setrate = setrate;
    }

    public Integer getRentMonth() {
		return rentMonth;
	}

	public void setRentMonth(Integer rentMonth) {
		this.rentMonth = rentMonth;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REASON
     *
     * @return the value of PRH_MASTER.REASON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REASON
     *
     * @param reason the value for PRH_MASTER.REASON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.NUMBS
     *
     * @return the value of PRH_MASTER.NUMBS
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getNumbs() {
        return numbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.NUMBS
     *
     * @param numbs the value for PRH_MASTER.NUMBS
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setNumbs(Integer numbs) {
        this.numbs = numbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.ARRTIME
     *
     * @return the value of PRH_MASTER.ARRTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getArrtime() {
        return arrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.ARRTIME
     *
     * @param arrtime the value for PRH_MASTER.ARRTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setArrtime(Date arrtime) {
        this.arrtime = arrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEP
     *
     * @return the value of PRH_MASTER.DEP
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getDep() {
        return dep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEP
     *
     * @param dep the value for PRH_MASTER.DEP
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDep(Date dep) {
        this.dep = dep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.ARR1
     *
     * @return the value of PRH_MASTER.ARR1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getArr1() {
        return arr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.ARR1
     *
     * @param arr1 the value for PRH_MASTER.ARR1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setArr1(Date arr1) {
        this.arr1 = arr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEP1
     *
     * @return the value of PRH_MASTER.DEP1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getDep1() {
        return dep1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEP1
     *
     * @param dep1 the value for PRH_MASTER.DEP1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDep1(Date dep1) {
        this.dep1 = dep1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEPOSIT
     *
     * @return the value of PRH_MASTER.DEPOSIT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEPOSIT
     *
     * @param deposit the value for PRH_MASTER.DEPOSIT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RENT_CODE
     *
     * @return the value of PRH_MASTER.RENT_CODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getRentCode() {
        return rentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RENT_CODE
     *
     * @param rentCode the value for PRH_MASTER.RENT_CODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRentCode(Integer rentCode) {
        this.rentCode = rentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RENT_DATE
     *
     * @return the value of PRH_MASTER.RENT_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getRentDate() {
        return rentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RENT_DATE
     *
     * @param rentDate the value for PRH_MASTER.RENT_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRentDate(Date rentDate) {
        this.rentDate = rentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REMARK
     *
     * @return the value of PRH_MASTER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REMARK
     *
     * @param remark the value for PRH_MASTER.REMARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PAYMENT
     *
     * @return the value of PRH_MASTER.PAYMENT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PAYMENT
     *
     * @param payment the value for PRH_MASTER.PAYMENT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.EXPEND
     *
     * @return the value of PRH_MASTER.EXPEND
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public BigDecimal getExpend() {
        return expend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.EXPEND
     *
     * @param expend the value for PRH_MASTER.EXPEND
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setExpend(BigDecimal expend) {
        this.expend = expend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CRT
     *
     * @return the value of PRH_MASTER.CRT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getCrt() {
        return crt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CRT
     *
     * @param crt the value for PRH_MASTER.CRT
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCrt(String crt) {
        this.crt = crt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CRTTIME
     *
     * @return the value of PRH_MASTER.CRTTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getCrttime() {
        return crttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CRTTIME
     *
     * @param crttime the value for PRH_MASTER.CRTTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCrttime(Date crttime) {
        this.crttime = crttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RES
     *
     * @return the value of PRH_MASTER.RES
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRes() {
        return res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RES
     *
     * @param res the value for PRH_MASTER.RES
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRes(String res) {
        this.res = res;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RESTIME
     *
     * @return the value of PRH_MASTER.RESTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getRestime() {
        return restime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RESTIME
     *
     * @param restime the value for PRH_MASTER.RESTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRestime(Date restime) {
        this.restime = restime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CON
     *
     * @return the value of PRH_MASTER.CON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CON
     *
     * @param con the value for PRH_MASTER.CON
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCon(String con) {
        this.con = con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CONTIME
     *
     * @return the value of PRH_MASTER.CONTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getContime() {
        return contime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CONTIME
     *
     * @param contime the value for PRH_MASTER.CONTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setContime(Date contime) {
        this.contime = contime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CI
     *
     * @return the value of PRH_MASTER.CI
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CI
     *
     * @param ci the value for PRH_MASTER.CI
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCi(String ci) {
        this.ci = ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CITIME
     *
     * @return the value of PRH_MASTER.CITIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getCitime() {
        return citime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CITIME
     *
     * @param citime the value for PRH_MASTER.CITIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCitime(Date citime) {
        this.citime = citime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CO
     *
     * @return the value of PRH_MASTER.CO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getCo() {
        return co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CO
     *
     * @param co the value for PRH_MASTER.CO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCo(String co) {
        this.co = co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.COTIME
     *
     * @return the value of PRH_MASTER.COTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getCotime() {
        return cotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.COTIME
     *
     * @param cotime the value for PRH_MASTER.COTIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCotime(Date cotime) {
        this.cotime = cotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.LOGID
     *
     * @return the value of PRH_MASTER.LOGID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.LOGID
     *
     * @param logid the value for PRH_MASTER.LOGID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setLogid(String logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.LOG_NAME
     *
     * @return the value of PRH_MASTER.LOG_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getLogName() {
        return logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.LOG_NAME
     *
     * @param logName the value for PRH_MASTER.LOG_NAME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setLogName(String logName) {
        this.logName = logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.LOG_DATE
     *
     * @return the value of PRH_MASTER.LOG_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.LOG_DATE
     *
     * @param logDate the value for PRH_MASTER.LOG_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.LOG_MARK
     *
     * @return the value of PRH_MASTER.LOG_MARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getLogMark() {
        return logMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.LOG_MARK
     *
     * @param logMark the value for PRH_MASTER.LOG_MARK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setLogMark(Integer logMark) {
        this.logMark = logMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BANK_FLAG
     *
     * @return the value of PRH_MASTER.BANK_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getBankFlag() {
        return bankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BANK_FLAG
     *
     * @param bankFlag the value for PRH_MASTER.BANK_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBankFlag(String bankFlag) {
        this.bankFlag = bankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BANK
     *
     * @return the value of PRH_MASTER.BANK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BANK
     *
     * @param bank the value for PRH_MASTER.BANK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BANK_NO
     *
     * @return the value of PRH_MASTER.BANK_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BANK_NO
     *
     * @param bankNo the value for PRH_MASTER.BANK_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEP_FLAG
     *
     * @return the value of PRH_MASTER.DEP_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getDepFlag() {
        return depFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEP_FLAG
     *
     * @param depFlag the value for PRH_MASTER.DEP_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDepFlag(String depFlag) {
        this.depFlag = depFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEP_APPLY
     *
     * @return the value of PRH_MASTER.DEP_APPLY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getDepApply() {
        return depApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEP_APPLY
     *
     * @param depApply the value for PRH_MASTER.DEP_APPLY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDepApply(Date depApply) {
        this.depApply = depApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DEP_FILE_NO
     *
     * @return the value of PRH_MASTER.DEP_FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getDepFileNo() {
        return depFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DEP_FILE_NO
     *
     * @param depFileNo the value for PRH_MASTER.DEP_FILE_NO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDepFileNo(String depFileNo) {
        this.depFileNo = depFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REL_FLAG
     *
     * @return the value of PRH_MASTER.REL_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRelFlag() {
        return relFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REL_FLAG
     *
     * @param relFlag the value for PRH_MASTER.REL_FLAG
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRelFlag(String relFlag) {
        this.relFlag = relFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.RELID
     *
     * @return the value of PRH_MASTER.RELID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRelid() {
        return relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.RELID
     *
     * @param relid the value for PRH_MASTER.RELID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRelid(String relid) {
        this.relid = relid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REL_DATE
     *
     * @return the value of PRH_MASTER.REL_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getRelDate() {
        return relDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REL_DATE
     *
     * @param relDate the value for PRH_MASTER.REL_DATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRelDate(Date relDate) {
        this.relDate = relDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REFER1
     *
     * @return the value of PRH_MASTER.REFER1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRefer1() {
        return refer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REFER1
     *
     * @param refer1 the value for PRH_MASTER.REFER1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRefer1(String refer1) {
        this.refer1 = refer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REFER2
     *
     * @return the value of PRH_MASTER.REFER2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRefer2() {
        return refer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REFER2
     *
     * @param refer2 the value for PRH_MASTER.REFER2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRefer2(String refer2) {
        this.refer2 = refer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REFER3
     *
     * @return the value of PRH_MASTER.REFER3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRefer3() {
        return refer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REFER3
     *
     * @param refer3 the value for PRH_MASTER.REFER3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRefer3(String refer3) {
        this.refer3 = refer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.REFER4
     *
     * @return the value of PRH_MASTER.REFER4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getRefer4() {
        return refer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.REFER4
     *
     * @param refer4 the value for PRH_MASTER.REFER4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setRefer4(String refer4) {
        this.refer4 = refer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BDATE2
     *
     * @return the value of PRH_MASTER.BDATE2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getBdate2() {
        return bdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BDATE2
     *
     * @param bdate2 the value for PRH_MASTER.BDATE2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBdate2(Date bdate2) {
        this.bdate2 = bdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.CUSNO
     *
     * @return the value of PRH_MASTER.CUSNO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getCusno() {
        return cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.CUSNO
     *
     * @param cusno the value for PRH_MASTER.CUSNO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setCusno(String cusno) {
        this.cusno = cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PRCODE
     *
     * @return the value of PRH_MASTER.PRCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getPrcode() {
        return prcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PRCODE
     *
     * @param prcode the value for PRH_MASTER.PRCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPrcode(String prcode) {
        this.prcode = prcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PDCODE
     *
     * @return the value of PRH_MASTER.PDCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getPdcode() {
        return pdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PDCODE
     *
     * @param pdcode the value for PRH_MASTER.PDCODE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPdcode(String pdcode) {
        this.pdcode = pdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.LOG_UPDATE
     *
     * @return the value of PRH_MASTER.LOG_UPDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getLogUpdate() {
        return logUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.LOG_UPDATE
     *
     * @param logUpdate the value for PRH_MASTER.LOG_UPDATE
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setLogUpdate(Date logUpdate) {
        this.logUpdate = logUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.BANK_REF
     *
     * @return the value of PRH_MASTER.BANK_REF
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getBankRef() {
        return bankRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.BANK_REF
     *
     * @param bankRef the value for PRH_MASTER.BANK_REF
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setBankRef(String bankRef) {
        this.bankRef = bankRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.TAG1
     *
     * @return the value of PRH_MASTER.TAG1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getTag1() {
        return tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.TAG1
     *
     * @param tag1 the value for PRH_MASTER.TAG1
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setTag1(String tag1) {
        this.tag1 = tag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.TAG2
     *
     * @return the value of PRH_MASTER.TAG2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getTag2() {
        return tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.TAG2
     *
     * @param tag2 the value for PRH_MASTER.TAG2
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setTag2(String tag2) {
        this.tag2 = tag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.TAG3
     *
     * @return the value of PRH_MASTER.TAG3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getTag3() {
        return tag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.TAG3
     *
     * @param tag3 the value for PRH_MASTER.TAG3
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setTag3(String tag3) {
        this.tag3 = tag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.TAG4
     *
     * @return the value of PRH_MASTER.TAG4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getTag4() {
        return tag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.TAG4
     *
     * @param tag4 the value for PRH_MASTER.TAG4
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setTag4(String tag4) {
        this.tag4 = tag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PIC_IDENTITY
     *
     * @return the value of PRH_MASTER.PIC_IDENTITY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getPicIdentity() {
        return picIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PIC_IDENTITY
     *
     * @param picIdentity the value for PRH_MASTER.PIC_IDENTITY
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPicIdentity(String picIdentity) {
        this.picIdentity = picIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PIC_PHOTO
     *
     * @return the value of PRH_MASTER.PIC_PHOTO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getPicPhoto() {
        return picPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PIC_PHOTO
     *
     * @param picPhoto the value for PRH_MASTER.PIC_PHOTO
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPicPhoto(String picPhoto) {
        this.picPhoto = picPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.PHYSICS_CARD_ID
     *
     * @return the value of PRH_MASTER.PHYSICS_CARD_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getPhysicsCardId() {
        return physicsCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.PHYSICS_CARD_ID
     *
     * @param physicsCardId the value for PRH_MASTER.PHYSICS_CARD_ID
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setPhysicsCardId(String physicsCardId) {
        this.physicsCardId = physicsCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.DOOR_LOCK
     *
     * @return the value of PRH_MASTER.DOOR_LOCK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public String getDoorLock() {
        return doorLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.DOOR_LOCK
     *
     * @param doorLock the value for PRH_MASTER.DOOR_LOCK
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setDoorLock(String doorLock) {
        this.doorLock = doorLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.UPDATE_TIME
     *
     * @return the value of PRH_MASTER.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.UPDATE_TIME
     *
     * @param updateTime the value for PRH_MASTER.UPDATE_TIME
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_MASTER.UPDATE_USER
     *
     * @return the value of PRH_MASTER.UPDATE_USER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_MASTER.UPDATE_USER
     *
     * @param updateUser the value for PRH_MASTER.UPDATE_USER
     *
     * @mbggenerated Fri May 12 13:44:15 CST 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

	public PrHouse getPrHouse() {
		return prHouse;
	}

	public void setPrHouse(PrHouse prHouse) {
		this.prHouse = prHouse;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public Integer getSubsidyTypeId() {
		return subsidyTypeId;
	}

	public void setSubsidyTypeId(Integer subsidyTypeId) {
		this.subsidyTypeId = subsidyTypeId;
	}

	public SubsidyType getSubsidyType() {
		return subsidyType;
	}

	public void setSubsidyType(SubsidyType subsidyType) {
		this.subsidyType = subsidyType;
	}

	public Integer getOldMasterId() {
		return oldMasterId;
	}

	public void setOldMasterId(Integer oldMasterId) {
		this.oldMasterId = oldMasterId;
	}

	public Double getTuidesposit() {
		return tuidesposit;
	}

	public void setTuidesposit(Double tuidesposit) {
		this.tuidesposit = tuidesposit;
	}
	private Double realPrice;
	
	private Double setRates;
	
	private Double shouldPrice;





	public Double getRealPrice() {
		return realPrice;
	}

	public void setRealPrice(Double realPrice) {
		this.realPrice = realPrice;
	}

	public Double getSetRates() {
		return setRates;
	}

	public void setSetRates(Double setRates) {
		this.setRates = setRates;
	}

	public Double getShouldPrice() {
		return shouldPrice;
	}

	public void setShouldPrice(Double shouldPrice) {
		this.shouldPrice = shouldPrice;
	}

    public Date getDeadlineofRent() {
        return deadlineofRent;
    }

    public void setDeadlineofRent(Date deadlineofRent) {
        this.deadlineofRent = deadlineofRent;
    }

    public Date getDeadlineofLock() {
        return deadlineofLock;
    }

    public void setDeadlineofLock(Date deadlineofLock) {
        this.deadlineofLock = deadlineofLock;
    }
}