package com.rent.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PrHouse {
	public PrHouse() {
		super();
	}
	public PrHouse(Integer id, String no, Integer estateId, String buildingNoId, String roomNo, Integer roomNoId,
			Integer buildingFloorId, Integer roomTypeId, BigDecimal area, Integer roomNum, BigDecimal price,
			BigDecimal monthPrice, BigDecimal backPrice, BigDecimal cheapPrice, Short state, String remark) {
		super();
		this.id = id;
		this.no = no;
		this.estateId = estateId;
		this.buildingNoId = buildingNoId;
		this.roomNo = roomNo;
		this.roomNoId = roomNoId;
		this.buildingFloorId = buildingFloorId;
		this.roomTypeId = roomTypeId;
		this.area = area;
		this.roomNum = roomNum;
		this.price = price;
		this.monthPrice = monthPrice;
		this.backPrice = backPrice;
		this.cheapPrice = cheapPrice;
		this.state = state;
		this.remark = remark;
	}

	private String reason;

	public PrHouse(String reason, String houseCode, Estate estate, BuildingNo buildingNo, BuildingFloor buildingFloor,
			RoomType roomType, PrhMaster prhMaster, Integer masterId, Integer id, String no, Integer estateId,
			String buildingNoId, String roomNo, Integer roomNoId, Integer buildingFloorId, Integer roomTypeId,
			BigDecimal area, Integer roomNum, BigDecimal price, BigDecimal monthPrice, BigDecimal backPrice,
			BigDecimal cheapPrice, Short state, String remark, BigDecimal rentMod, Date modDate, Date decDate,
			String decMan) {
		super();
		this.reason = reason;
		this.houseCode = houseCode;
		this.estate = estate;
		this.buildingNo = buildingNo;
		this.buildingFloor = buildingFloor;
		this.roomType = roomType;
		this.prhMaster = prhMaster;
		this.masterId = masterId;
		this.id = id;
		this.no = no;
		this.estateId = estateId;
		this.buildingNoId = buildingNoId;
		this.roomNo = roomNo;
		this.roomNoId = roomNoId;
		this.buildingFloorId = buildingFloorId;
		this.roomTypeId = roomTypeId;
		this.area = area;
		this.roomNum = roomNum;
		this.price = price;
		this.monthPrice = monthPrice;
		this.backPrice = backPrice;
		this.cheapPrice = cheapPrice;
		this.state = state;
		this.remark = remark;
		this.rentMod = rentMod;
		this.modDate = modDate;
		this.decDate = decDate;
		this.decMan = decMan;
		
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	private Integer isTui;
	private String houseCode;
	private Estate estate;
	private BuildingNo buildingNo;
	private BuildingFloor buildingFloor;
	private RoomType roomType;
	private PrhMaster prhMaster;

	private String createuser;

	private Date createtime;

	private String updateuser;

	private Date updatetime;
	private Short originState;

	private String associatedlock;

	public String getAssociatedlock() {
		return associatedlock;
	}

	public void setAssociatedlock(String associatedlock) {
		this.associatedlock = associatedlock;
	}

	public String getCreateuser() {
		return createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getUpdateuser() {
		return updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	public Date getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getHouseCode() {
		return houseCode;
	}

	public void setHouseCode(String houseCode) {
		this.houseCode = houseCode;
	}

	public Estate getEstate() {
		return estate;
	}

	public void setEstate(Estate estate) {
		this.estate = estate;
	}

	public BuildingNo getBuildingNo() {
		return buildingNo;
	}

	public void setBuildingNo(BuildingNo buildingNo) {
		this.buildingNo = buildingNo;
	}

	public BuildingFloor getBuildingFloor() {
		return buildingFloor;
	}

	public void setBuildingFloor(BuildingFloor buildingFloor) {
		this.buildingFloor = buildingFloor;
	}

	public RoomType getRoomType() {
		return roomType;
	}

	public void setRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	private Integer masterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private String no;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.ESTATE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Integer estateId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.BUILDING_NO_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private String buildingNoId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.ROOM_NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private String roomNo;

	private Integer roomNoId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.BUILDING_FLOOR_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Integer buildingFloorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.ROOM_TYPE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Integer roomTypeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.AREA
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private BigDecimal area;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.ROOM_NUM
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Integer roomNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private BigDecimal price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.MONTH_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private BigDecimal monthPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.BACK_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private BigDecimal backPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.CHEAP_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private BigDecimal cheapPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.STATE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private Short state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PR_HOUSE.REMARK
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.ID
	 *
	 * @return the value of PR_HOUSE.ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.ID
	 *
	 * @param id
	 *            the value for PR_HOUSE.ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.NO
	 *
	 * @return the value of PR_HOUSE.NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.NO
	 *
	 * @param no
	 *            the value for PR_HOUSE.NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.ESTATE_ID
	 *
	 * @return the value of PR_HOUSE.ESTATE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Integer getEstateId() {
		return estateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.ESTATE_ID
	 *
	 * @param estateId
	 *            the value for PR_HOUSE.ESTATE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setEstateId(Integer estateId) {
		this.estateId = estateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.BUILDING_NO_ID
	 *
	 * @return the value of PR_HOUSE.BUILDING_NO_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public String getBuildingNoId() {
		return buildingNoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.BUILDING_NO_ID
	 *
	 * @param buildingNoId
	 *            the value for PR_HOUSE.BUILDING_NO_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setBuildingNoId(String buildingNoId) {
		this.buildingNoId = buildingNoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.ROOM_NO
	 *
	 * @return the value of PR_HOUSE.ROOM_NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public String getRoomNo() {
		return roomNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.ROOM_NO
	 *
	 * @param roomNo
	 *            the value for PR_HOUSE.ROOM_NO
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.BUILDING_FLOOR_ID
	 *
	 * @return the value of PR_HOUSE.BUILDING_FLOOR_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Integer getBuildingFloorId() {
		return buildingFloorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.BUILDING_FLOOR_ID
	 *
	 * @param buildingFloorId
	 *            the value for PR_HOUSE.BUILDING_FLOOR_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setBuildingFloorId(Integer buildingFloorId) {
		this.buildingFloorId = buildingFloorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.ROOM_TYPE_ID
	 *
	 * @return the value of PR_HOUSE.ROOM_TYPE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Integer getRoomTypeId() {
		return roomTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.ROOM_TYPE_ID
	 *
	 * @param roomTypeId
	 *            the value for PR_HOUSE.ROOM_TYPE_ID
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setRoomTypeId(Integer roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.AREA
	 *
	 * @return the value of PR_HOUSE.AREA
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public BigDecimal getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.AREA
	 *
	 * @param area
	 *            the value for PR_HOUSE.AREA
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setArea(BigDecimal area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.ROOM_NUM
	 *
	 * @return the value of PR_HOUSE.ROOM_NUM
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Integer getRoomNum() {
		return roomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.ROOM_NUM
	 *
	 * @param roomNum
	 *            the value for PR_HOUSE.ROOM_NUM
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setRoomNum(Integer roomNum) {
		this.roomNum = roomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.PRICE
	 *
	 * @return the value of PR_HOUSE.PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.PRICE
	 *
	 * @param price
	 *            the value for PR_HOUSE.PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.MONTH_PRICE
	 *
	 * @return the value of PR_HOUSE.MONTH_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public BigDecimal getMonthPrice() {
		return monthPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.MONTH_PRICE
	 *
	 * @param monthPrice
	 *            the value for PR_HOUSE.MONTH_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setMonthPrice(BigDecimal monthPrice) {
		this.monthPrice = monthPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.BACK_PRICE
	 *
	 * @return the value of PR_HOUSE.BACK_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public BigDecimal getBackPrice() {
		return backPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.BACK_PRICE
	 *
	 * @param backPrice
	 *            the value for PR_HOUSE.BACK_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setBackPrice(BigDecimal backPrice) {
		this.backPrice = backPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.CHEAP_PRICE
	 *
	 * @return the value of PR_HOUSE.CHEAP_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public BigDecimal getCheapPrice() {
		return cheapPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.CHEAP_PRICE
	 *
	 * @param cheapPrice
	 *            the value for PR_HOUSE.CHEAP_PRICE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setCheapPrice(BigDecimal cheapPrice) {
		this.cheapPrice = cheapPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.STATE
	 *
	 * @return the value of PR_HOUSE.STATE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public Short getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.STATE
	 *
	 * @param state
	 *            the value for PR_HOUSE.STATE
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setState(Short state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PR_HOUSE.REMARK
	 *
	 * @return the value of PR_HOUSE.REMARK
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PR_HOUSE.REMARK
	 *
	 * @param remark
	 *            the value for PR_HOUSE.REMARK
	 *
	 * @mbggenerated Thu May 04 11:37:29 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getRoomNoId() {
		return roomNoId;
	}

	public void setRoomNoId(Integer roomNoId) {
		this.roomNoId = roomNoId;
	}

	public PrhMaster getPrhMaster() {
		return prhMaster;
	}

	public void setPrhMaster(PrhMaster prhMaster) {
		this.prhMaster = prhMaster;
	}

	public Integer getMasterId() {
		return masterId;
	}

	public void setMasterId(Integer masterId) {
		this.masterId = masterId;
	}

	private BigDecimal rentMod;
	private Date modDate;
	private Date decDate;
	private String decMan;

	public PrHouse(String houseCode, Estate estate, BuildingNo buildingNo, BuildingFloor buildingFloor,
			RoomType roomType, PrhMaster prhMaster, Integer masterId, Integer id, String no, Integer estateId,
			String buildingNoId, String roomNo, Integer roomNoId, Integer buildingFloorId, Integer roomTypeId,
			BigDecimal area, Integer roomNum, BigDecimal price, BigDecimal monthPrice, BigDecimal backPrice,
			BigDecimal cheapPrice, Short state, String remark, BigDecimal rentMod, Date modDate, Date decDate,
			String decMan) {
		super();
		this.houseCode = houseCode;
		this.estate = estate;
		this.buildingNo = buildingNo;
		this.buildingFloor = buildingFloor;
		this.roomType = roomType;
		this.prhMaster = prhMaster;
		this.masterId = masterId;
		this.id = id;
		this.no = no;
		this.estateId = estateId;
		this.buildingNoId = buildingNoId;
		this.roomNo = roomNo;
		this.roomNoId = roomNoId;
		this.buildingFloorId = buildingFloorId;
		this.roomTypeId = roomTypeId;
		this.area = area;
		this.roomNum = roomNum;
		this.price = price;
		this.monthPrice = monthPrice;
		this.backPrice = backPrice;
		this.cheapPrice = cheapPrice;
		this.state = state;
		this.remark = remark;
		this.rentMod = rentMod;
		this.modDate = modDate;
		this.decDate = decDate;
		this.decMan = decMan;
	}

	public Date getDecDate() {
		return decDate;
	}

	public void setDecDate(Date decDate) {
		this.decDate = decDate;
	}

	public String getDecMan() {
		return decMan;
	}

	public void setDecMan(String decMan) {
		this.decMan = decMan;
	}

	public BigDecimal getRentMod() {
		return rentMod;
	}

	public void setRentMod(BigDecimal rentMod) {
		this.rentMod = rentMod;
	}

	public Date getModDate() {
		return modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public PrHouse(String houseCode, Estate estate, BuildingNo buildingNo, BuildingFloor buildingFloor,
			RoomType roomType, PrhMaster prhMaster, Integer masterId, Integer id, String no, Integer estateId,
			String buildingNoId, String roomNo, Integer roomNoId, Integer buildingFloorId, Integer roomTypeId,
			BigDecimal area, Integer roomNum, BigDecimal price, BigDecimal monthPrice, BigDecimal backPrice,
			BigDecimal cheapPrice, Short state, String remark, BigDecimal rentMod, Date modDate) {
		super();
		this.houseCode = houseCode;
		this.estate = estate;
		this.buildingNo = buildingNo;
		this.buildingFloor = buildingFloor;
		this.roomType = roomType;
		this.prhMaster = prhMaster;
		this.masterId = masterId;
		this.id = id;
		this.no = no;
		this.estateId = estateId;
		this.buildingNoId = buildingNoId;
		this.roomNo = roomNo;
		this.roomNoId = roomNoId;
		this.buildingFloorId = buildingFloorId;
		this.roomTypeId = roomTypeId;
		this.area = area;
		this.roomNum = roomNum;
		this.price = price;
		this.monthPrice = monthPrice;
		this.backPrice = backPrice;
		this.cheapPrice = cheapPrice;
		this.state = state;
		this.remark = remark;
		this.rentMod = rentMod;
		this.modDate = modDate;
	}
	public Short getOriginState() {
		return originState;
	}
	public void setOriginState(Short originState) {
		this.originState = originState;
	}
	public Integer getIsTui() {
		return isTui;
	}
	public void setIsTui(Integer isTui) {
		this.isTui = isTui;
	}

}