package com.rent.entity;

public class PrhPaycode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_PAYCODE.ID
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_PAYCODE.NAME
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_PAYCODE.ID
     *
     * @return the value of PRH_PAYCODE.ID
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_PAYCODE.ID
     *
     * @param id the value for PRH_PAYCODE.ID
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_PAYCODE.NAME
     *
     * @return the value of PRH_PAYCODE.NAME
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_PAYCODE.NAME
     *
     * @param name the value for PRH_PAYCODE.NAME
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}