package com.rent.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PrhRental {
   
	private PrhMaster accnts;
	private PrHouse houses;

	
	public PrhMaster getAccnts() {
		return accnts;
	}

	public void setAccnts(PrhMaster accnts) {
		this.accnts = accnts;
	}

	public PrHouse getHouses() {
		return houses;
	}

	public void setHouses(PrHouse houses) {
		this.houses = houses;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ACCNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer accnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.INUMBER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer inumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.FLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ORGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.PRTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String prtno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.NAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.GUESTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String guestno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.VROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String vroomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.RMTYPE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String rmtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.RATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.FILENO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String fileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.DEPOSIT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Double charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE6
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE7
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE8
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CHARGE9
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal charge9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.BDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date bdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.EDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date edate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.AMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.REF1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ref1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.REF2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ref2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.REF3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ref3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.REF4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ref4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.REF5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ref5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.PRTID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String prtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.PRTNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String prtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.PRTDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date prtdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.PRTTIMES
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer prttimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.STA
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CASHIER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String cashier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CASHNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String cashname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CASHDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date cashdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.sysdate
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date sysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.AUDIT1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String audit1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.LOGID1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String logid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.AUDIT1TIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date audit1time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.AUDIT2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String audit2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.LOGID2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String logid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.AUDITTIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.IFLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String iflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.IAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal iamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.INO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ILOGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ilogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ILOGNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String ilogname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ISYSDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date isysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.ILOGDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date ilogdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.METHOD
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.OROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String oroomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.DAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.FMONTHS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer fmonths;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.FDAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Integer fdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.FAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private BigDecimal famount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.CUSNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private String cusno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRH_RENTAL.LOGUPDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    private Date logupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ID
     *
     * @return the value of PRH_RENTAL.ID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ID
     *
     * @param id the value for PRH_RENTAL.ID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ACCNT
     *
     * @return the value of PRH_RENTAL.ACCNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getAccnt() {
        return accnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ACCNT
     *
     * @param accnt the value for PRH_RENTAL.ACCNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAccnt(Integer accnt) {
        this.accnt = accnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.INUMBER
     *
     * @return the value of PRH_RENTAL.INUMBER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getInumber() {
        return inumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.INUMBER
     *
     * @param inumber the value for PRH_RENTAL.INUMBER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setInumber(Integer inumber) {
        this.inumber = inumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.FLAG
     *
     * @return the value of PRH_RENTAL.FLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.FLAG
     *
     * @param flag the value for PRH_RENTAL.FLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ORGID
     *
     * @return the value of PRH_RENTAL.ORGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ORGID
     *
     * @param orgid the value for PRH_RENTAL.ORGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.PRTNO
     *
     * @return the value of PRH_RENTAL.PRTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getPrtno() {
        return prtno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.PRTNO
     *
     * @param prtno the value for PRH_RENTAL.PRTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setPrtno(String prtno) {
        this.prtno = prtno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.NAME
     *
     * @return the value of PRH_RENTAL.NAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.NAME
     *
     * @param name the value for PRH_RENTAL.NAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.GUESTNO
     *
     * @return the value of PRH_RENTAL.GUESTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getGuestno() {
        return guestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.GUESTNO
     *
     * @param guestno the value for PRH_RENTAL.GUESTNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setGuestno(String guestno) {
        this.guestno = guestno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ROOMNO
     *
     * @return the value of PRH_RENTAL.ROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ROOMNO
     *
     * @param roomno the value for PRH_RENTAL.ROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.VROOMNO
     *
     * @return the value of PRH_RENTAL.VROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getVroomno() {
        return vroomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.VROOMNO
     *
     * @param vroomno the value for PRH_RENTAL.VROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setVroomno(String vroomno) {
        this.vroomno = vroomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.RMTYPE
     *
     * @return the value of PRH_RENTAL.RMTYPE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRmtype() {
        return rmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.RMTYPE
     *
     * @param rmtype the value for PRH_RENTAL.RMTYPE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRmtype(String rmtype) {
        this.rmtype = rmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.RATE
     *
     * @return the value of PRH_RENTAL.RATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.RATE
     *
     * @param rate the value for PRH_RENTAL.RATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.FILENO
     *
     * @return the value of PRH_RENTAL.FILENO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getFileno() {
        return fileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.FILENO
     *
     * @param fileno the value for PRH_RENTAL.FILENO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setFileno(String fileno) {
        this.fileno = fileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.DEPOSIT
     *
     * @return the value of PRH_RENTAL.DEPOSIT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.DEPOSIT
     *
     * @param deposit the value for PRH_RENTAL.DEPOSIT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE
     *
     * @return the value of PRH_RENTAL.CHARGE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Double getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE
     *
     * @param charge the value for PRH_RENTAL.CHARGE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge(Double charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE1
     *
     * @return the value of PRH_RENTAL.CHARGE1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge1() {
        return charge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE1
     *
     * @param charge1 the value for PRH_RENTAL.CHARGE1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge1(BigDecimal charge1) {
        this.charge1 = charge1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE2
     *
     * @return the value of PRH_RENTAL.CHARGE2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge2() {
        return charge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE2
     *
     * @param charge2 the value for PRH_RENTAL.CHARGE2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge2(BigDecimal charge2) {
        this.charge2 = charge2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE3
     *
     * @return the value of PRH_RENTAL.CHARGE3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge3() {
        return charge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE3
     *
     * @param charge3 the value for PRH_RENTAL.CHARGE3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge3(BigDecimal charge3) {
        this.charge3 = charge3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE4
     *
     * @return the value of PRH_RENTAL.CHARGE4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge4() {
        return charge4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE4
     *
     * @param charge4 the value for PRH_RENTAL.CHARGE4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge4(BigDecimal charge4) {
        this.charge4 = charge4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE5
     *
     * @return the value of PRH_RENTAL.CHARGE5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge5() {
        return charge5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE5
     *
     * @param charge5 the value for PRH_RENTAL.CHARGE5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge5(BigDecimal charge5) {
        this.charge5 = charge5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE6
     *
     * @return the value of PRH_RENTAL.CHARGE6
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge6() {
        return charge6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE6
     *
     * @param charge6 the value for PRH_RENTAL.CHARGE6
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge6(BigDecimal charge6) {
        this.charge6 = charge6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE7
     *
     * @return the value of PRH_RENTAL.CHARGE7
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge7() {
        return charge7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE7
     *
     * @param charge7 the value for PRH_RENTAL.CHARGE7
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge7(BigDecimal charge7) {
        this.charge7 = charge7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE8
     *
     * @return the value of PRH_RENTAL.CHARGE8
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge8() {
        return charge8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE8
     *
     * @param charge8 the value for PRH_RENTAL.CHARGE8
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge8(BigDecimal charge8) {
        this.charge8 = charge8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CHARGE9
     *
     * @return the value of PRH_RENTAL.CHARGE9
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getCharge9() {
        return charge9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CHARGE9
     *
     * @param charge9 the value for PRH_RENTAL.CHARGE9
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCharge9(BigDecimal charge9) {
        this.charge9 = charge9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.BDATE
     *
     * @return the value of PRH_RENTAL.BDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getBdate() {
        return bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.BDATE
     *
     * @param bdate the value for PRH_RENTAL.BDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.EDATE
     *
     * @return the value of PRH_RENTAL.EDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.EDATE
     *
     * @param edate the value for PRH_RENTAL.EDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.AMOUNT
     *
     * @return the value of PRH_RENTAL.AMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.AMOUNT
     *
     * @param amount the value for PRH_RENTAL.AMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.REF1
     *
     * @return the value of PRH_RENTAL.REF1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRef1() {
        return ref1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.REF1
     *
     * @param ref1 the value for PRH_RENTAL.REF1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRef1(String ref1) {
        this.ref1 = ref1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.REF2
     *
     * @return the value of PRH_RENTAL.REF2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRef2() {
        return ref2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.REF2
     *
     * @param ref2 the value for PRH_RENTAL.REF2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRef2(String ref2) {
        this.ref2 = ref2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.REF3
     *
     * @return the value of PRH_RENTAL.REF3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRef3() {
        return ref3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.REF3
     *
     * @param ref3 the value for PRH_RENTAL.REF3
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRef3(String ref3) {
        this.ref3 = ref3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.REF4
     *
     * @return the value of PRH_RENTAL.REF4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRef4() {
        return ref4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.REF4
     *
     * @param ref4 the value for PRH_RENTAL.REF4
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRef4(String ref4) {
        this.ref4 = ref4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.REF5
     *
     * @return the value of PRH_RENTAL.REF5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getRef5() {
        return ref5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.REF5
     *
     * @param ref5 the value for PRH_RENTAL.REF5
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setRef5(String ref5) {
        this.ref5 = ref5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.PRTID
     *
     * @return the value of PRH_RENTAL.PRTID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getPrtid() {
        return prtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.PRTID
     *
     * @param prtid the value for PRH_RENTAL.PRTID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setPrtid(String prtid) {
        this.prtid = prtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.PRTNAME
     *
     * @return the value of PRH_RENTAL.PRTNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getPrtname() {
        return prtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.PRTNAME
     *
     * @param prtname the value for PRH_RENTAL.PRTNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setPrtname(String prtname) {
        this.prtname = prtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.PRTDATE
     *
     * @return the value of PRH_RENTAL.PRTDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getPrtdate() {
        return prtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.PRTDATE
     *
     * @param prtdate the value for PRH_RENTAL.PRTDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setPrtdate(Date prtdate) {
        this.prtdate = prtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.PRTTIMES
     *
     * @return the value of PRH_RENTAL.PRTTIMES
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getPrttimes() {
        return prttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.PRTTIMES
     *
     * @param prttimes the value for PRH_RENTAL.PRTTIMES
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setPrttimes(Integer prttimes) {
        this.prttimes = prttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.STA
     *
     * @return the value of PRH_RENTAL.STA
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.STA
     *
     * @param sta the value for PRH_RENTAL.STA
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setSta(String sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CASHIER
     *
     * @return the value of PRH_RENTAL.CASHIER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getCashier() {
        return cashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CASHIER
     *
     * @param cashier the value for PRH_RENTAL.CASHIER
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCashier(String cashier) {
        this.cashier = cashier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CASHNAME
     *
     * @return the value of PRH_RENTAL.CASHNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getCashname() {
        return cashname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CASHNAME
     *
     * @param cashname the value for PRH_RENTAL.CASHNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCashname(String cashname) {
        this.cashname = cashname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CASHDATE
     *
     * @return the value of PRH_RENTAL.CASHDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getCashdate() {
        return cashdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CASHDATE
     *
     * @param cashdate the value for PRH_RENTAL.CASHDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCashdate(Date cashdate) {
        this.cashdate = cashdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.sysdate
     *
     * @return the value of PRH_RENTAL.sysdate
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getSysdate() {
        return sysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.sysdate
     *
     * @param sysdate the value for PRH_RENTAL.sysdate
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setSysdate(Date sysdate) {
        this.sysdate = sysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.AUDIT1
     *
     * @return the value of PRH_RENTAL.AUDIT1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getAudit1() {
        return audit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.AUDIT1
     *
     * @param audit1 the value for PRH_RENTAL.AUDIT1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAudit1(String audit1) {
        this.audit1 = audit1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.LOGID1
     *
     * @return the value of PRH_RENTAL.LOGID1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getLogid1() {
        return logid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.LOGID1
     *
     * @param logid1 the value for PRH_RENTAL.LOGID1
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setLogid1(String logid1) {
        this.logid1 = logid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.AUDIT1TIME
     *
     * @return the value of PRH_RENTAL.AUDIT1TIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getAudit1time() {
        return audit1time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.AUDIT1TIME
     *
     * @param audit1time the value for PRH_RENTAL.AUDIT1TIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAudit1time(Date audit1time) {
        this.audit1time = audit1time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.AUDIT2
     *
     * @return the value of PRH_RENTAL.AUDIT2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getAudit2() {
        return audit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.AUDIT2
     *
     * @param audit2 the value for PRH_RENTAL.AUDIT2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAudit2(String audit2) {
        this.audit2 = audit2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.LOGID2
     *
     * @return the value of PRH_RENTAL.LOGID2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getLogid2() {
        return logid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.LOGID2
     *
     * @param logid2 the value for PRH_RENTAL.LOGID2
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setLogid2(String logid2) {
        this.logid2 = logid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.AUDITTIME
     *
     * @return the value of PRH_RENTAL.AUDITTIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.AUDITTIME
     *
     * @param audittime the value for PRH_RENTAL.AUDITTIME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.IFLAG
     *
     * @return the value of PRH_RENTAL.IFLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getIflag() {
        return iflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.IFLAG
     *
     * @param iflag the value for PRH_RENTAL.IFLAG
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIflag(String iflag) {
        this.iflag = iflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.IAMOUNT
     *
     * @return the value of PRH_RENTAL.IAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getIamount() {
        return iamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.IAMOUNT
     *
     * @param iamount the value for PRH_RENTAL.IAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIamount(BigDecimal iamount) {
        this.iamount = iamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.INO
     *
     * @return the value of PRH_RENTAL.INO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getIno() {
        return ino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.INO
     *
     * @param ino the value for PRH_RENTAL.INO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIno(String ino) {
        this.ino = ino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ILOGID
     *
     * @return the value of PRH_RENTAL.ILOGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getIlogid() {
        return ilogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ILOGID
     *
     * @param ilogid the value for PRH_RENTAL.ILOGID
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIlogid(String ilogid) {
        this.ilogid = ilogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ILOGNAME
     *
     * @return the value of PRH_RENTAL.ILOGNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getIlogname() {
        return ilogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ILOGNAME
     *
     * @param ilogname the value for PRH_RENTAL.ILOGNAME
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIlogname(String ilogname) {
        this.ilogname = ilogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ISYSDATE
     *
     * @return the value of PRH_RENTAL.ISYSDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getIsysdate() {
        return isysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ISYSDATE
     *
     * @param isysdate the value for PRH_RENTAL.ISYSDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIsysdate(Date isysdate) {
        this.isysdate = isysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.ILOGDATE
     *
     * @return the value of PRH_RENTAL.ILOGDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getIlogdate() {
        return ilogdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.ILOGDATE
     *
     * @param ilogdate the value for PRH_RENTAL.ILOGDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setIlogdate(Date ilogdate) {
        this.ilogdate = ilogdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.METHOD
     *
     * @return the value of PRH_RENTAL.METHOD
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.METHOD
     *
     * @param method the value for PRH_RENTAL.METHOD
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.OROOMNO
     *
     * @return the value of PRH_RENTAL.OROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getOroomno() {
        return oroomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.OROOMNO
     *
     * @param oroomno the value for PRH_RENTAL.OROOMNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setOroomno(String oroomno) {
        this.oroomno = oroomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.DAYS
     *
     * @return the value of PRH_RENTAL.DAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.DAYS
     *
     * @param days the value for PRH_RENTAL.DAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.FMONTHS
     *
     * @return the value of PRH_RENTAL.FMONTHS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getFmonths() {
        return fmonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.FMONTHS
     *
     * @param fmonths the value for PRH_RENTAL.FMONTHS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setFmonths(Integer fmonths) {
        this.fmonths = fmonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.FDAYS
     *
     * @return the value of PRH_RENTAL.FDAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Integer getFdays() {
        return fdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.FDAYS
     *
     * @param fdays the value for PRH_RENTAL.FDAYS
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setFdays(Integer fdays) {
        this.fdays = fdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.FAMOUNT
     *
     * @return the value of PRH_RENTAL.FAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public BigDecimal getFamount() {
        return famount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.FAMOUNT
     *
     * @param famount the value for PRH_RENTAL.FAMOUNT
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setFamount(BigDecimal famount) {
        this.famount = famount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.CUSNO
     *
     * @return the value of PRH_RENTAL.CUSNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public String getCusno() {
        return cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.CUSNO
     *
     * @param cusno the value for PRH_RENTAL.CUSNO
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setCusno(String cusno) {
        this.cusno = cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRH_RENTAL.LOGUPDATE
     *
     * @return the value of PRH_RENTAL.LOGUPDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public Date getLogupdate() {
        return logupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRH_RENTAL.LOGUPDATE
     *
     * @param logupdate the value for PRH_RENTAL.LOGUPDATE
     *
     * @mbggenerated Mon May 22 21:23:27 CST 2017
     */
    public void setLogupdate(Date logupdate) {
        this.logupdate = logupdate;
    }
}