package com.rent.entity;

import java.math.BigDecimal;

public class RentPayWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.DEPOSIT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private Integer depositPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.RENT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private Integer rentPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.mode
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.DAY_OR_MONTH
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private Integer dayOrMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.DESCRIPT1
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String descript1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.DESCRIPT2
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String descript2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_PAY_WAY.DESCRIPT3
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    private String descript3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.ID
     *
     * @return the value of RENT_PAY_WAY.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.ID
     *
     * @param id the value for RENT_PAY_WAY.ID
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.NAME
     *
     * @return the value of RENT_PAY_WAY.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.NAME
     *
     * @param name the value for RENT_PAY_WAY.NAME
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.DEPOSIT_PAY
     *
     * @return the value of RENT_PAY_WAY.DEPOSIT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public Integer getDepositPay() {
        return depositPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.DEPOSIT_PAY
     *
     * @param depositPay the value for RENT_PAY_WAY.DEPOSIT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setDepositPay(Integer depositPay) {
        this.depositPay = depositPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.RENT_PAY
     *
     * @return the value of RENT_PAY_WAY.RENT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public Integer getRentPay() {
        return rentPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.RENT_PAY
     *
     * @param rentPay the value for RENT_PAY_WAY.RENT_PAY
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setRentPay(Integer rentPay) {
        this.rentPay = rentPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.mode
     *
     * @return the value of RENT_PAY_WAY.mode
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.mode
     *
     * @param mode the value for RENT_PAY_WAY.mode
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.DAY_OR_MONTH
     *
     * @return the value of RENT_PAY_WAY.DAY_OR_MONTH
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public Integer getDayOrMonth() {
        return dayOrMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.DAY_OR_MONTH
     *
     * @param dayOrMonth the value for RENT_PAY_WAY.DAY_OR_MONTH
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setDayOrMonth(Integer dayOrMonth) {
        this.dayOrMonth = dayOrMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.DESCRIPT1
     *
     * @return the value of RENT_PAY_WAY.DESCRIPT1
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getDescript1() {
        return descript1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.DESCRIPT1
     *
     * @param descript1 the value for RENT_PAY_WAY.DESCRIPT1
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setDescript1(String descript1) {
        this.descript1 = descript1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.DESCRIPT2
     *
     * @return the value of RENT_PAY_WAY.DESCRIPT2
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getDescript2() {
        return descript2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.DESCRIPT2
     *
     * @param descript2 the value for RENT_PAY_WAY.DESCRIPT2
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setDescript2(String descript2) {
        this.descript2 = descript2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_PAY_WAY.DESCRIPT3
     *
     * @return the value of RENT_PAY_WAY.DESCRIPT3
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public String getDescript3() {
        return descript3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_PAY_WAY.DESCRIPT3
     *
     * @param descript3 the value for RENT_PAY_WAY.DESCRIPT3
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    public void setDescript3(String descript3) {
        this.descript3 = descript3;
    }
}