package com.rent.entity;

import java.util.Date;

public class RentMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.PARENT_ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.PARENT_IDS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.NAME
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.SORT
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.HREF
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.TARGET
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.ICON
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.IS_SHOW
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.PERMISSION
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.CREATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.UPDATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.REMARKS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private Object remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RENT_MENU.DEL_FLAG
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.ID
     *
     * @return the value of RENT_MENU.ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.ID
     *
     * @param id the value for RENT_MENU.ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.PARENT_ID
     *
     * @return the value of RENT_MENU.PARENT_ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.PARENT_ID
     *
     * @param parentId the value for RENT_MENU.PARENT_ID
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.PARENT_IDS
     *
     * @return the value of RENT_MENU.PARENT_IDS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.PARENT_IDS
     *
     * @param parentIds the value for RENT_MENU.PARENT_IDS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.NAME
     *
     * @return the value of RENT_MENU.NAME
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.NAME
     *
     * @param name the value for RENT_MENU.NAME
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.SORT
     *
     * @return the value of RENT_MENU.SORT
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.SORT
     *
     * @param sort the value for RENT_MENU.SORT
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.HREF
     *
     * @return the value of RENT_MENU.HREF
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.HREF
     *
     * @param href the value for RENT_MENU.HREF
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.TARGET
     *
     * @return the value of RENT_MENU.TARGET
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.TARGET
     *
     * @param target the value for RENT_MENU.TARGET
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.ICON
     *
     * @return the value of RENT_MENU.ICON
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.ICON
     *
     * @param icon the value for RENT_MENU.ICON
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.IS_SHOW
     *
     * @return the value of RENT_MENU.IS_SHOW
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.IS_SHOW
     *
     * @param isShow the value for RENT_MENU.IS_SHOW
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.PERMISSION
     *
     * @return the value of RENT_MENU.PERMISSION
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.PERMISSION
     *
     * @param permission the value for RENT_MENU.PERMISSION
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.CREATE_BY
     *
     * @return the value of RENT_MENU.CREATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.CREATE_BY
     *
     * @param createBy the value for RENT_MENU.CREATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.CREATE_DATE
     *
     * @return the value of RENT_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.CREATE_DATE
     *
     * @param createDate the value for RENT_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.UPDATE_BY
     *
     * @return the value of RENT_MENU.UPDATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.UPDATE_BY
     *
     * @param updateBy the value for RENT_MENU.UPDATE_BY
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.UPDATE_DATE
     *
     * @return the value of RENT_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.UPDATE_DATE
     *
     * @param updateDate the value for RENT_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.REMARKS
     *
     * @return the value of RENT_MENU.REMARKS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public Object getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.REMARKS
     *
     * @param remarks the value for RENT_MENU.REMARKS
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setRemarks(Object remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RENT_MENU.DEL_FLAG
     *
     * @return the value of RENT_MENU.DEL_FLAG
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RENT_MENU.DEL_FLAG
     *
     * @param delFlag the value for RENT_MENU.DEL_FLAG
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}