package com.rent.entity;

import java.math.BigDecimal;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.ID
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.YEAR
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.MONTH
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    private Short month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.DAY
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    private Short day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.TOTAL
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    private BigDecimal total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.ID
     *
     * @return the value of REPORT.ID
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.ID
     *
     * @param id the value for REPORT.ID
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.YEAR
     *
     * @return the value of REPORT.YEAR
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.YEAR
     *
     * @param year the value for REPORT.YEAR
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.MONTH
     *
     * @return the value of REPORT.MONTH
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public Short getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.MONTH
     *
     * @param month the value for REPORT.MONTH
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public void setMonth(Short month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.DAY
     *
     * @return the value of REPORT.DAY
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public Short getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.DAY
     *
     * @param day the value for REPORT.DAY
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public void setDay(Short day) {
    	
    	
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.TOTAL
     *
     * @return the value of REPORT.TOTAL
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.TOTAL
     *
     * @param total the value for REPORT.TOTAL
     *
     * @mbggenerated Fri Jun 30 18:38:26 CST 2017
     */
    public void setTotal(BigDecimal total) {
    	total=BigDecimal.valueOf(Double.parseDouble(String.format("%.2f",total)));
    	
    	total  =  BigDecimal.valueOf(total.setScale(2,   BigDecimal.ROUND_HALF_UP).doubleValue());  
        this.total = total;
    }
}