package com.rent.entity;

import java.math.BigDecimal;

public class RmdevTemp2 {

	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMDEV_TEMP.ID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMDEV_TEMP.ROOMTYPE
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    private String roomtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMDEV_TEMP.CLA
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    private String cla;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMDEV_TEMP.EQID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    private BigDecimal eqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMDEV_TEMP.NUM
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    private BigDecimal num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMDEV_TEMP.ID
     *
     * @return the value of RMDEV_TEMP.ID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMDEV_TEMP.ID
     *
     * @param id the value for RMDEV_TEMP.ID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMDEV_TEMP.ROOMTYPE
     *
     * @return the value of RMDEV_TEMP.ROOMTYPE
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMDEV_TEMP.ROOMTYPE
     *
     * @param roomtype the value for RMDEV_TEMP.ROOMTYPE
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMDEV_TEMP.CLA
     *
     * @return the value of RMDEV_TEMP.CLA
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public String getCla() {
        return cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMDEV_TEMP.CLA
     *
     * @param cla the value for RMDEV_TEMP.CLA
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public void setCla(String cla) {
        this.cla = cla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMDEV_TEMP.EQID
     *
     * @return the value of RMDEV_TEMP.EQID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public BigDecimal getEqid() {
        return eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMDEV_TEMP.EQID
     *
     * @param eqid the value for RMDEV_TEMP.EQID
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public void setEqid(BigDecimal eqid) {
        this.eqid = eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMDEV_TEMP.NUM
     *
     * @return the value of RMDEV_TEMP.NUM
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMDEV_TEMP.NUM
     *
     * @param num the value for RMDEV_TEMP.NUM
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }
}
