package com.rent.entity;

public class RoomType {

	public RoomType() {
		super();
	}

	

	public RoomType(Integer id, String no, String name, String descript,
			String remark) {
		super();
		this.id = id;
		this.no = no;
		this.name = name;
		this.descript = descript;
		this.remark = remark;
	}



	private Integer id;
	
	private String no;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROOM_TYPE.NAME
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROOM_TYPE.DESCRIPT
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	private String descript;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROOM_TYPE.REMARK
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROOM_TYPE.ID
	 * 
	 * @return the value of ROOM_TYPE.ID
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROOM_TYPE.NAME
	 * 
	 * @param name
	 *            the value for ROOM_TYPE.NAME
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	
	public void setName(String name) {
		this.name = name;
	}

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROOM_TYPE.DESCRIPT
	 * 
	 * @return the value of ROOM_TYPE.DESCRIPT
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROOM_TYPE.DESCRIPT
	 * 
	 * @param descript
	 *            the value for ROOM_TYPE.DESCRIPT
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROOM_TYPE.REMARK
	 * 
	 * @return the value of ROOM_TYPE.REMARK
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROOM_TYPE.REMARK
	 * 
	 * @param remark
	 *            the value for ROOM_TYPE.REMARK
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

}