package com.rent.entity;

public class RoomFeature {

	public RoomFeature() {
		super();
	}

	public RoomFeature(Integer id, String no, String name,String remark) {
		super();
		this.id = id;
		this.no = no;
		this.name = name;
		this.remark=remark;
	}

	private Integer id;
	private String no;

	private String name;
	private String remark;
	
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return name;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROOM_FEATURE.NAME
	 * 
	 * @param name
	 *            the value for ROOM_FEATURE.NAME
	 * 
	 * @mbggenerated Tue Apr 25 15:59:09 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}