package com.rent.entity;

public class RoomEstateProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.PROJECT_IN_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String projectInName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.SUPERIOR_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String superiorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.ADDRESS
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.PHONE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOM_ESTATE_PROJECT.OFFICE_TIME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    private String officeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.ID
     *
     * @return the value of ROOM_ESTATE_PROJECT.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.ID
     *
     * @param id the value for ROOM_ESTATE_PROJECT.ID
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.PROJECT_IN_NAME
     *
     * @return the value of ROOM_ESTATE_PROJECT.PROJECT_IN_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getProjectInName() {
        return projectInName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.PROJECT_IN_NAME
     *
     * @param projectInName the value for ROOM_ESTATE_PROJECT.PROJECT_IN_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setProjectInName(String projectInName) {
        this.projectInName = projectInName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.SUPERIOR_NAME
     *
     * @return the value of ROOM_ESTATE_PROJECT.SUPERIOR_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getSuperiorName() {
        return superiorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.SUPERIOR_NAME
     *
     * @param superiorName the value for ROOM_ESTATE_PROJECT.SUPERIOR_NAME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setSuperiorName(String superiorName) {
        this.superiorName = superiorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.ADDRESS
     *
     * @return the value of ROOM_ESTATE_PROJECT.ADDRESS
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.ADDRESS
     *
     * @param address the value for ROOM_ESTATE_PROJECT.ADDRESS
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.PHONE
     *
     * @return the value of ROOM_ESTATE_PROJECT.PHONE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.PHONE
     *
     * @param phone the value for ROOM_ESTATE_PROJECT.PHONE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOM_ESTATE_PROJECT.OFFICE_TIME
     *
     * @return the value of ROOM_ESTATE_PROJECT.OFFICE_TIME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public String getOfficeTime() {
        return officeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOM_ESTATE_PROJECT.OFFICE_TIME
     *
     * @param officeTime the value for ROOM_ESTATE_PROJECT.OFFICE_TIME
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    public void setOfficeTime(String officeTime) {
        this.officeTime = officeTime;
    }
}