package com.rent.entity;

public class Student {
    
	
	private Teacher teacher;
	
	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.TEACHER_ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.ID
     *
     * @return the value of STUDENT.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.ID
     *
     * @param id the value for STUDENT.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.NAME
     *
     * @return the value of STUDENT.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.NAME
     *
     * @param name the value for STUDENT.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.TEACHER_ID
     *
     * @return the value of STUDENT.TEACHER_ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.TEACHER_ID
     *
     * @param teacherId the value for STUDENT.TEACHER_ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}