package com.rent.entity;

public class SubsidyType {
	
	
	
    public SubsidyType() {
		super();
	}

	public SubsidyType(Integer id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_TYPE.ID
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
	
	
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_TYPE.NAME
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_TYPE.ID
     *
     * @return the value of SUBSIDY_TYPE.ID
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_TYPE.ID
     *
     * @param id the value for SUBSIDY_TYPE.ID
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_TYPE.NAME
     *
     * @return the value of SUBSIDY_TYPE.NAME
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_TYPE.NAME
     *
     * @param name the value for SUBSIDY_TYPE.NAME
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}