package com.rent.entity;

import java.math.BigDecimal;

public class SubsidyPercent {
    
	
	public SubsidyPercent() {
		super();
	}

	public SubsidyPercent(Integer id, BigDecimal inLowObject, BigDecimal inLow,
			BigDecimal inMiddle, BigDecimal outLowObject, BigDecimal outLow,
			BigDecimal outMiddle, BigDecimal updateTime, BigDecimal updateUser) {
		super();
		this.id = id;
		this.inLowObject = inLowObject;
		this.inLow = inLow;
		this.inMiddle = inMiddle;
		this.outLowObject = outLowObject;
		this.outLow = outLow;
		this.outMiddle = outMiddle;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.ID
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.IN_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal inLowObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.IN_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal inLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.IN_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal inMiddle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.OUT_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal outLowObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.OUT_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal outLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.OUT_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal outMiddle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_PERCENT.UPDATE_USER
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    private BigDecimal updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.ID
     *
     * @return the value of SUBSIDY_PERCENT.ID
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.ID
     *
     * @param id the value for SUBSIDY_PERCENT.ID
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.IN_LOW_OBJECT
     *
     * @return the value of SUBSIDY_PERCENT.IN_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getInLowObject() {
        return inLowObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.IN_LOW_OBJECT
     *
     * @param inLowObject the value for SUBSIDY_PERCENT.IN_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setInLowObject(BigDecimal inLowObject) {
        this.inLowObject = inLowObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.IN_LOW
     *
     * @return the value of SUBSIDY_PERCENT.IN_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getInLow() {
        return inLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.IN_LOW
     *
     * @param inLow the value for SUBSIDY_PERCENT.IN_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setInLow(BigDecimal inLow) {
        this.inLow = inLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.IN_MIDDLE
     *
     * @return the value of SUBSIDY_PERCENT.IN_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getInMiddle() {
        return inMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.IN_MIDDLE
     *
     * @param inMiddle the value for SUBSIDY_PERCENT.IN_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setInMiddle(BigDecimal inMiddle) {
        this.inMiddle = inMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.OUT_LOW_OBJECT
     *
     * @return the value of SUBSIDY_PERCENT.OUT_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getOutLowObject() {
        return outLowObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.OUT_LOW_OBJECT
     *
     * @param outLowObject the value for SUBSIDY_PERCENT.OUT_LOW_OBJECT
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setOutLowObject(BigDecimal outLowObject) {
        this.outLowObject = outLowObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.OUT_LOW
     *
     * @return the value of SUBSIDY_PERCENT.OUT_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getOutLow() {
        return outLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.OUT_LOW
     *
     * @param outLow the value for SUBSIDY_PERCENT.OUT_LOW
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setOutLow(BigDecimal outLow) {
        this.outLow = outLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.OUT_MIDDLE
     *
     * @return the value of SUBSIDY_PERCENT.OUT_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getOutMiddle() {
        return outMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.OUT_MIDDLE
     *
     * @param outMiddle the value for SUBSIDY_PERCENT.OUT_MIDDLE
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setOutMiddle(BigDecimal outMiddle) {
        this.outMiddle = outMiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.UPDATE_TIME
     *
     * @return the value of SUBSIDY_PERCENT.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.UPDATE_TIME
     *
     * @param updateTime the value for SUBSIDY_PERCENT.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setUpdateTime(BigDecimal updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_PERCENT.UPDATE_USER
     *
     * @return the value of SUBSIDY_PERCENT.UPDATE_USER
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public BigDecimal getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_PERCENT.UPDATE_USER
     *
     * @param updateUser the value for SUBSIDY_PERCENT.UPDATE_USER
     *
     * @mbggenerated Wed May 03 17:21:11 CST 2017
     */
    public void setUpdateUser(BigDecimal updateUser) {
        this.updateUser = updateUser;
    }
}