package com.rent.entity;

import java.math.BigDecimal;

public class SubsidyWithType {
   
	public SubsidyWithType() {
		super();
	}

	public SubsidyWithType(Integer id, Integer subsidyId, Integer typeId,
			Integer inOrOut, Double percent) {
		super();
		this.id = id;
		this.subsidyId = subsidyId;
		this.typeId = typeId;
		this.inOrOut = inOrOut;
		this.percent = percent;
	}
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_WITH_TYPE.ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_WITH_TYPE.SUBSIDY_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    private Integer subsidyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_WITH_TYPE.TYPE_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_WITH_TYPE.IN_OR_OUT
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    private Integer inOrOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBSIDY_WITH_TYPE.PERCENT
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    private Double percent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_WITH_TYPE.ID
     *
     * @return the value of SUBSIDY_WITH_TYPE.ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_WITH_TYPE.ID
     *
     * @param id the value for SUBSIDY_WITH_TYPE.ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_WITH_TYPE.SUBSIDY_ID
     *
     * @return the value of SUBSIDY_WITH_TYPE.SUBSIDY_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public Integer getSubsidyId() {
        return subsidyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_WITH_TYPE.SUBSIDY_ID
     *
     * @param subsidyId the value for SUBSIDY_WITH_TYPE.SUBSIDY_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public void setSubsidyId(Integer subsidyId) {
        this.subsidyId = subsidyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_WITH_TYPE.TYPE_ID
     *
     * @return the value of SUBSIDY_WITH_TYPE.TYPE_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_WITH_TYPE.TYPE_ID
     *
     * @param typeId the value for SUBSIDY_WITH_TYPE.TYPE_ID
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBSIDY_WITH_TYPE.IN_OR_OUT
     *
     * @return the value of SUBSIDY_WITH_TYPE.IN_OR_OUT
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public Integer getInOrOut() {
        return inOrOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBSIDY_WITH_TYPE.IN_OR_OUT
     *
     * @param inOrOut the value for SUBSIDY_WITH_TYPE.IN_OR_OUT
     *
     * @mbggenerated Fri May 05 11:50:00 CST 2017
     */
    public void setInOrOut(Integer inOrOut) {
        this.inOrOut = inOrOut;
    }

	public Double getPercent() {
		return percent;
	}

	public void setPercent(Double percent) {
		this.percent = percent;
	}


}