package com.rent.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.ID
     *
     * @return the value of TEACHER.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.ID
     *
     * @param id the value for TEACHER.ID
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.NAME
     *
     * @return the value of TEACHER.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.NAME
     *
     * @param name the value for TEACHER.NAME
     *
     * @mbggenerated Mon Jun 26 16:02:15 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}