package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.AccntSelected;

@MyBatisDao
public interface AccntSelectedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(AccntSelected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(AccntSelected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    AccntSelected selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(AccntSelected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCNT_SELECTED
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(AccntSelected record);
}