package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Attachment;
@MyBatisDao
public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    Attachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated Fri Jun 16 12:25:41 CST 2017
     */
    int updateByPrimaryKey(Attachment record);
    
    List<Attachment> findByMaster(Integer masterId);
    
    List<Attachment> findAll();
    
    Integer deleteByMaster(Integer masterId);
}