package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BillData;

@MyBatisDao
public interface BillDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(BillData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(BillData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    BillData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(BillData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DATA
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(BillData record);
}