package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BillPcprint;

@MyBatisDao
public interface BillPcprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(BillPcprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(BillPcprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    BillPcprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(BillPcprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_PCPRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(BillPcprint record);
}