package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BillUnit;

@MyBatisDao
public interface BillUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(BillUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(BillUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    BillUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(BillUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_UNIT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(BillUnit record);
}