package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BillDefault;

@MyBatisDao
public interface BillDefaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(BillDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(BillDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    BillDefault selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(BillDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_DEFAULT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(BillDefault record);
}