package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BillMode;

@MyBatisDao
public interface BillModeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(BillMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(BillMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    BillMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(BillMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILL_MODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(BillMode record);
}