package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.BuildingFloor;

@MyBatisDao
public interface BuildingFloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insert(BuildingFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insertSelective(BuildingFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    BuildingFloor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(BuildingFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUILDING_FLOOR
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKey(BuildingFloor record);
    /**
     * 查询全部
     * @return 楼层集合
     */
    List<BuildingFloor> findAll();
    
     /**
     * 查询总数
     * @return 总数
     */
    int selectTotalCount();
    
    List<BuildingFloor> getAllPaged(Integer begin,Integer end);
    
    
    
}