package com.rent.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Card;
@MyBatisDao
public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    Card selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD
     *
     * @mbggenerated Thu Jun 01 21:11:18 CST 2017
     */
    int updateByPrimaryKey(Card record);
    /**
     * 条件查询卡
     * @param masterId
     * @param linkId
     * @param type
     * @param state
     * @return
     */
    List<Card> findByMasterAndLink(@Param("masterId") Integer masterId,@Param("linkId")Integer linkId,@Param("type")Integer type,@Param("state")Integer state);
    
    Integer getNextId();
    
    Integer getAuthorizeIdSeq();
    
    Integer getRoomNumSeq();
    
    Integer getRoomIdSeq();
    
}