package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.CostCode;
import com.rent.entity.RoomFeature;

@MyBatisDao
public interface CostCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    int insert(CostCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    int insertSelective(CostCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    CostCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    int updateByPrimaryKeySelective(CostCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COST_CODE
     *
     * @mbggenerated Tue May 02 16:18:40 CST 2017
     */
    int updateByPrimaryKey(CostCode record);
    /**
     * 查询总数
     * @return 总数
     */
     int getTotalCount();
     /**
      * 分页查询
      * @param begin
      * @param end
      * @return 集合
      */
     List<CostCode> findAllPaged(int begin,int end);
}