package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.DoorParm;

@MyBatisDao
public interface DoorParmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(DoorParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(DoorParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    DoorParm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(DoorParm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_PARM
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(DoorParm record);
}