package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.DoorRoomno;

@MyBatisDao
public interface DoorRoomnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(DoorRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(DoorRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    DoorRoomno selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(DoorRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOOR_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(DoorRoomno record);
}