package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Equipment;
@MyBatisDao
public interface EquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    int insertSelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    Equipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    int updateByPrimaryKeySelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */
    int updateByPrimaryKey(Equipment record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Wed May 17 19:45:58 CST 2017
     */ 
    
    List<Equipment> findAllPaged(Integer begin,Integer end);
    Integer getTotalCount();
    List<Equipment> findAllEqu();
}