package com.rent.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.HistoryIdenPwd;
@MyBatisDao
public interface HistoryIdenPwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    int insert(HistoryIdenPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    int insertSelective(HistoryIdenPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    HistoryIdenPwd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    int updateByPrimaryKeySelective(HistoryIdenPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY_IDEN_PWD
     *
     * @mbggenerated Fri Jun 23 15:01:38 CST 2017
     */
    int updateByPrimaryKey(HistoryIdenPwd record);
    
    List<HistoryIdenPwd> findAll();
    
    List<HistoryIdenPwd> findByPerson(@Param("masterId")Integer masterId,@Param("linkId")Integer linkId);
}