package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.HouseSpace;
@MyBatisDao
public interface HouseSpaceMapper {
   
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_SPACE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    int insert(HouseSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_SPACE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    int insertSelective(HouseSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_SPACE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    HouseSpace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_SPACE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    int updateByPrimaryKeySelective(HouseSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOUSE_SPACE
     *
     * @mbggenerated Mon May 22 15:01:39 CST 2017
     */
    int updateByPrimaryKey(HouseSpace record);
    /**
     * 查询上一次房间空闲记录
     * @param houseId
     * @return
     */
    List<HouseSpace> findLastRecord(Integer houseId);
}