package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Module;
@MyBatisDao
public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    Module selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODULE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int updateByPrimaryKey(Module record);
    
    
    
    List<Module> findByCondition(Module module);
    
    
    List<Module> findChildrenById(Integer pid);
    
}