package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Pbcatcol;

@MyBatisDao
public interface PbcatcolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(Pbcatcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(Pbcatcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    Pbcatcol selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(Pbcatcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATCOL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(Pbcatcol record);
}