package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Pbcatedt;

@MyBatisDao
public interface PbcatedtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(Pbcatedt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(Pbcatedt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    Pbcatedt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(Pbcatedt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATEDT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(Pbcatedt record);
}