package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Pbcatfmt;

@MyBatisDao
public interface PbcatfmtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(Pbcatfmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(Pbcatfmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    Pbcatfmt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(Pbcatfmt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATFMT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(Pbcatfmt record);
}