package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Pbcattbl;

@MyBatisDao
public interface PbcattblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(Pbcattbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(Pbcattbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    Pbcattbl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(Pbcattbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PBCATTBL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(Pbcattbl record);
}