package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhBalDef;

@MyBatisDao
public interface PrhBalDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhBalDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhBalDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhBalDef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhBalDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL_DEF
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhBalDef record);
}