package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhBal22;

@MyBatisDao
public interface PrhBal22Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhBal22 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhBal22 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhBal22 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhBal22 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_BAL22
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhBal22 record);
}