package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhCode;

@MyBatisDao
public interface PrhCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CODE
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhCode record);
}