package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhCheckout;

@MyBatisDao
public interface PrhCheckoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhCheckout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhCheckout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhCheckout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhCheckout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_CHECKOUT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhCheckout record);
}