package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhDevTmp3;

@MyBatisDao
public interface PrhDevTmp3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhDevTmp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhDevTmp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhDevTmp3 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhDevTmp3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP3
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhDevTmp3 record);
}