package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhDevTmp2;

@MyBatisDao
public interface PrhDevTmp2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhDevTmp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhDevTmp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhDevTmp2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhDevTmp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_DEV_TMP2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhDevTmp2 record);
}