package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhImp;

@MyBatisDao
public interface PrhImpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhImp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhImp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhImp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhImp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_IMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhImp record);
}