package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhLinkman;
@MyBatisDao
public interface PrhLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    int insert(PrhLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    int insertSelective(PrhLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    PrhLinkman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    int updateByPrimaryKeySelective(PrhLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_LINKMAN
     *
     * @mbggenerated Sat May 13 20:25:14 CST 2017
     */
    int updateByPrimaryKey(PrhLinkman record);
    
    
    List<PrhLinkman> getAllByMaster(int masterId);
    
    
}