package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhMasterRenew;

@MyBatisDao
public interface PrhMasterRenewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhMasterRenew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhMasterRenew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhMasterRenew selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhMasterRenew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_RENEW
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhMasterRenew record);
}