package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhMasterPrint;

@MyBatisDao
public interface PrhMasterPrintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhMasterPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhMasterPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhMasterPrint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhMasterPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_MASTER_PRINT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhMasterPrint record);
}