package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhPaycode;
@MyBatisDao
public interface PrhPaycodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYCODE
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    int insert(PrhPaycode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYCODE
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    int insertSelective(PrhPaycode record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYCODE
     *
     * @mbggenerated Wed May 24 15:37:52 CST 2017
     */
    List<PrhPaycode> findAllPayCode();
}