package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhPayment;

@MyBatisDao
public interface PrhPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhPayment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhPayment record);
    
    Integer  findMaxId();
    
    List<PrhPayment> findByAccntId(Integer accntId);
    
    PrhPayment findByPrtNo(Integer id);
    
    List<PrhPayment> findByMasterIdAndHistory(Integer id);
}