package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhPayment2;

@MyBatisDao
public interface PrhPayment2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhPayment2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhPayment2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhPayment2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhPayment2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_PAYMENT2
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhPayment2 record);
}