package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRoomnoTmp;

@MyBatisDao
public interface PrhRoomnoTmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRoomnoTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRoomnoTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRoomnoTmp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRoomnoTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO_TMP
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRoomnoTmp record);
}