package com.rent.dao;

import java.util.Date;
import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.condition.HouseAndDateCondition;
import com.rent.condition.RenDaliyCondition;
import com.rent.condition.RenterCondition;
import com.rent.entity.PrhRental;

@MyBatisDao
public interface PrhRentalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRental record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRental record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRental selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRental record);
    
    
    int  updateByMasterId(PrhRental prhRental);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRental record);
    /**
     * This method was generated by MyBatis Generator.
     * 根据条件查询总数
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    
    Integer findCountByCondition(RenterCondition rental);
    
    /**
     * This method was generated by MyBatis Generator.
     * 根据分页查询
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    List<PrhRental>  findByConditionAndPaged(RenterCondition rental);
    //根据id 查询
    PrhRental findById(Integer id);
    
    List<PrhRental>  findByAccnt(Integer accnt);

    Integer  findMaxId();
    
    
    int delByMaster(int master);
    
    List<PrhRental>  findByMasterId(Integer masterId);

	List<PrhRental> findArrears(Date date);

	Integer findCountByExpiringCondition(RenDaliyCondition condition);

	List<PrhRental> findCountByExpiringConditionAndPaged(RenDaliyCondition condition);

	List<PrhRental> findByAccntAndDate(HouseAndDateCondition condition);

}