package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRentalMonth;

@MyBatisDao
public interface PrhRentalMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRentalMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRentalMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRentalMonth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRentalMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_MONTH
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRentalMonth record);
}