package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRmooo;

@MyBatisDao
public interface PrhRmoooMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRmooo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRmooo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRmooo selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRmooo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMOOO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRmooo record);
}