package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRmrateAdjust;

@MyBatisDao
public interface PrhRmrateAdjustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRmrateAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRmrateAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRmrateAdjust selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRmrateAdjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMRATE_ADJUST
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRmrateAdjust record);
}