package com.rent.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.condition.HouseFileContion;
import com.rent.condition.RmdevCondition;
import com.rent.entity.PrhRmdev;

@MyBatisDao
public interface PrhRmdevMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRmdev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRmdev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRmdev selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRmdev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRmdev record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateStateByid(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    List<PrhRmdev> findById(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    List<PrhRmdev> findByConditionPaged(RmdevCondition condition);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RMDEV
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    Integer findMaxID();
    
    
}