package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRoomno;

@MyBatisDao
public interface PrhRoomnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRoomno selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRoomno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_ROOMNO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRoomno record);
}