package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhRentalDel;

@MyBatisDao
public interface PrhRentalDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhRentalDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhRentalDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhRentalDel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhRentalDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_RENTAL_DEL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhRentalDel record);
}