package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhSubsidyDtl;

@MyBatisDao
public interface PrhSubsidyDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhSubsidyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhSubsidyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhSubsidyDtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhSubsidyDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY_DTL
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhSubsidyDtl record);
}