package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.PrhSubsidy;

@MyBatisDao
public interface PrhSubsidyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(String bno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(PrhSubsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(PrhSubsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    PrhSubsidy selectByPrimaryKey(String bno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrhSubsidy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRH_SUBSIDY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(PrhSubsidy record);
}