package com.rent.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.condition.FileCondition;
import com.rent.entity.PrhMaster;
import com.rent.entity.Profile;

@MyBatisDao
public interface ProfileMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	int deleteByPrimaryKey(String guestno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	int insert(Profile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	int insertSelective(Profile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	Profile selectByPrimaryKey(String guestno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	int updateByPrimaryKeySelective(Profile record);
	
		
		
	int updateByCusNoSelective(Profile profile);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE
	 *
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	
	int updateByPrimaryKey(Profile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE 多条件查询单位档案信息
	 * 
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	List<Profile> findProfileByCondition(@Param("cla") String cla, @Param("sta") String sta,
			@Param("name") String name);

	List<Profile> findProfileByCondition1(FileCondition condition);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PROFILE 多条件分页查询单位档案信息
	 * 
	 * @mbggenerated Mon Apr 24 14:56:49 CST 2017
	 */
	List<Profile> findProfileByConditionAndPage(@Param("cla") String cla, @Param("sta") String sta,
			@Param("name") String name, @Param("begin") Integer begin, @Param("end") Integer end);

	List<Profile> findProfileByConditionAndPage1(FileCondition condition);

	/**
	 * 根据身份证查询
	 * 
	 * @param cardId
	 * @return
	 */
	List<Profile> findByCardId(String cardId);

	/**
	 * 根据gusetNo 查询
	 * 
	 * @param gusetNo
	 * @return
	 */
	Profile findBygusetNo(@Param("guestNo") String guestno);

	/**
	 * 查询所有公司
	 * 
	 * @return 公司
	 */
	List<Profile> findAllCompanyByEstateId(Integer estateId);

	String findNameByHouseId(Integer houseid);

	List<Profile> findProfileByCondition2(FileCondition condition);

	List<Profile> findProfileByConditionAndPage2(FileCondition condition);

	// 通过物业查询公司（分页）
	List<Profile> findCompanyByEstatePaged(@Param("estateId")Integer estateId, @Param("begin")Integer begin, @Param("end")Integer end,@Param("company") String company);
	// 通过物业查询公司总数
	Integer findCompanyByEstateCount(@Param("estateId")Integer estateId,@Param("company") String company);
	

}