package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RentMenu;
@MyBatisDao
public interface RentMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    int insert(RentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    int insertSelective(RentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    RentMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    int updateByPrimaryKeySelective(RentMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RENT_MENU
     *
     * @mbggenerated Mon Jun 05 14:26:54 CST 2017
     */
    int updateByPrimaryKey(RentMenu record);
}