package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.condition.TempCondition;
import com.rent.entity.RmdevTemp;
@MyBatisDao
public interface RmdevTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMDEV_TEMP
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    int insert(RmdevTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMDEV_TEMP
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    int insertSelective(RmdevTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMDEV_TEMP
     *
     * @mbggenerated Wed May 17 20:46:37 CST 2017
     */
    List<RmdevTemp> findByRoid(Integer roid);
    
    List<RmdevTemp> findByRoidAndPaged(TempCondition condition);
    //查询最大id
    Integer findMaxId();
    
    int deleteByPrimaryKey(Integer id);
    int updateByPrimaryKey(RmdevTemp record);   
    RmdevTemp selectByPrimaryKey(Integer id);
    //通过房间类型删除
    Integer delByRoomType(Integer typeId);
}