package com.rent.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.Role;
@MyBatisDao
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 04 17:36:23 CST 2017
     */
    int updateByPrimaryKey(Role record);
    
    List<Role> findAll();
    
    List<Role> findByName(String name);
    
    Integer getOnUseNum(@Param("roleId")Integer roleId);
    
}