package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RoomType;

@MyBatisDao
public interface RoomTypeMapper {
    Integer findMaxId ();

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    RoomType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_TYPE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKey(RoomType record);
    /**
     * ��ѯȫ��
     * @return roomType����
     */
    List<RoomType> findAll();
    
    /**
     * ��ҳ��ѯȫ��
     * @param begin
     * @param end
     * @return
     */
    List<RoomType> findAllByPaged(int begin, int end);
    
    /**
     * ��ѯ����
     * @return ����
     */
    Integer getTotalCount();
    
    /**
     * �������Ʋ��Ҷ���
     * @param ����
     * @return ����
     */
    RoomType findByName(String name);
}