package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RoomFeature;

@MyBatisDao
public interface RoomFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insert(RoomFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insertSelective(RoomFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    RoomFeature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(RoomFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_FEATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKey(RoomFeature record);
   /**
    * 查询总数
    * @return 总数
    */
    int getTotalCount();
    /**
     * 分页查询
     * @param begin
     * @param end
     * @return 集合
     */
    List<RoomFeature> findAllPaged(int begin,int end);
}