package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RoomNature;

@MyBatisDao
public interface RoomNatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insert(RoomNature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insertSelective(RoomNature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    RoomNature selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(RoomNature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_NATURE
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKey(RoomNature record);
}