package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RoomEstateProject;

@MyBatisDao
public interface RoomEstateProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insert(RoomEstateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int insertSelective(RoomEstateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    RoomEstateProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKeySelective(RoomEstateProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOM_ESTATE_PROJECT
     *
     * @mbggenerated Tue Apr 25 15:59:09 CST 2017
     */
    int updateByPrimaryKey(RoomEstateProject record);
}