package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.SmsCode;

@MyBatisDao
public interface SmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    int insert(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    int insertSelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    SmsCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    int updateByPrimaryKeySelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_CODE
     *
     * @mbggenerated Mon Apr 24 15:07:41 CST 2017
     */
    int updateByPrimaryKey(SmsCode record);
}