package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.SmsKfolio;

@MyBatisDao
public interface SmsKfolioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KFOLIO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(SmsKfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KFOLIO
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(SmsKfolio record);
}