package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.SmsKeywords;

@MyBatisDao
public interface SmsKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(SmsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(SmsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    SmsKeywords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(SmsKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_KEYWORDS
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(SmsKeywords record);
}