package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.SmsLibrary;

@MyBatisDao
public interface SmsLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(SmsLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(SmsLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    SmsLibrary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(SmsLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_LIBRARY
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(SmsLibrary record);
}