package com.rent.dao;

import java.util.List;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.RoomType;
import com.rent.entity.SubsidyType;

@MyBatisDao
public interface SubsidyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    int insert(SubsidyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    int insertSelective(SubsidyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    SubsidyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    int updateByPrimaryKeySelective(SubsidyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBSIDY_TYPE
     *
     * @mbggenerated Fri May 05 10:29:45 CST 2017
     */
    int updateByPrimaryKey(SubsidyType SubsidyType);
    
    /**
     * 查询全部
     * @return subsidyType集合
     */
    List<SubsidyType> findAll();
    
    /**
     * 分页查询全部
     * @param begin
     * @param end
     * @return
     */
    List<SubsidyType> findAllByPaged(int begin, int end);
    
    /**
     * 查询总数
     * @return 总数
     */
    Integer getTotalCount();
    
    /**
     * 根据名称查找对象
     * @param 名称
     * @return 对象
     */
    SubsidyType findByName(String name);
}