package com.rent.dao;

import com.rent.common.persistence.annotation.MyBatisDao;
import com.rent.entity.TableLog;

@MyBatisDao
public interface TableLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insert(TableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int insertSelective(TableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    TableLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(TableLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_LOG
     *
     * @mbggenerated Mon Apr 24 14:56:49 CST 2017
     */
    int updateByPrimaryKey(TableLog record);
}